/** Where freighters fly from: the pilot's own bridge process, one extra `Account` per freighter.
 * A freighter has no bridge, juncture or pilot record of its own. Its whole state is a row of
 * `freighters.json` in the pilot's runtime dir, its script is `freighters/<name>.ts` (generated by
 * `assign`), and its login is `freighters/<name>.txt`, which the operator puts there.
 *
 * A loop never touches the play runtime singleton: it commands through its own account, and
 * journals into the pilot's journal under a `<name>:` prefix. Not reachable from a pilot file
 * (`play/freighter` resolves to `index.ts`, never here). */
import {Account,type GameState} from '@spacemolt/lib';
import {createHash} from 'node:crypto';
import {existsSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {controllerLock} from '../../controller-lock.ts';
import {GAME_WS_URL,readCredentials} from '../../credentials.ts';
import type {ReadinessAccount,ReadinessCommand} from '../../readiness.ts';
import {journalCommand,journalRun} from '../../run-record.ts';
import {pilotHome} from '../../run.ts';
import {checkBoundary,specifiers} from '../boundary.ts';
import {checkPolicy} from '../policy.ts';
import type {Circuit} from '../trading/trading.ts';
import type {Freighter,Holding} from './index.ts';

/** One freighter as `freighters.json` keeps it. */
export interface Entry {
  /** `running` flies (and is resumed after a restart); `recalling` finishes its stop; `parked` is stopped for good. */
  state:'running'|'recalling'|'parked';
  circuit:Circuit;float:number;owner:string;
  /** Laps completed since it was assigned, the base it is at or was last at, its wallet there. */
  lap:number;stop?:string;credits?:number;
  /** Credits deposited home to `owner`, all told. */
  returned:number;
  /** The last whole lap's net, against `circuit.lap_net` predicted: the wallet's change plus the
   * change in `holding`. */
  last_lap_net?:number;
  /** The cargo aboard it bought, at cost, after its last stop. */
  holding?:Holding;
  /** Why it parked, or what fell short at the last stop. */
  why?:string;
  at:string;
}
/** A freighter as `freighters()` and the menu report it. */
export interface FreighterRow {name:string;state:Entry['state'];lap:number;stop:string|null;credits:number|null;
  returned:number;last_lap_net:number|null;lap_net:number;holding:Holding;why?:string}

const FILE='freighters.json',RETRY_MS=60_000;
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
const sha=(text:string|Buffer)=>createHash('sha256').update(text).digest('hex');

export const scriptPath=(runtime:string,name:string)=>join(runtime,'freighters',`${name}.ts`);
export const credentialsPath=(runtime:string,name:string)=>join(runtime,'freighters',`${name}.txt`);

export function readFleet(runtime:string):Record<string,Entry> {
  try {const fleet=JSON.parse(readFileSync(join(runtime,FILE),'utf8'));return fleet&&typeof fleet==='object'?fleet:{};}
  catch {return {};}
}
/** Temp file then rename: a torn write would resume a freighter on a lie. */
export function writeFleet(runtime:string,fleet:Record<string,Entry>):void {
  const path=join(runtime,FILE),temp=`${path}.${process.pid}.tmp`;
  writeFileSync(temp,JSON.stringify(fleet,null,2),{mode:0o600});
  renameSync(temp,path);
}
function update(runtime:string,name:string,fields:Partial<Entry>):void {
  const fleet=readFleet(runtime);
  if(!fleet[name])return;
  fleet[name]={...fleet[name],...fields,at:new Date().toISOString()};
  writeFleet(runtime,fleet);
}

export const row=(name:string,entry:Entry):FreighterRow=>({name,state:entry.state,lap:entry.lap,stop:entry.stop??null,
  credits:entry.credits??null,returned:entry.returned,last_lap_net:entry.last_lap_net??null,lap_net:entry.circuit.lap_net,
  holding:entry.holding??{},...entry.why?{why:entry.why}:{}});
/** `holding` in words: `40 copper_piping (1148 cr)`. */
export const held=(holding:Holding)=>Object.entries(holding).map(([item,row])=>`${row.quantity} ${item} (${Math.round(row.cost)} cr)`).join(', ');
/** The menu's `freighters` rows; nothing when none was ever assigned. */
export function fleetBrief(runtime:string):{freighters?:FreighterRow[]} {
  const rows=Object.entries(readFleet(runtime)).map(([name,entry])=>row(name,entry));
  return rows.length?{freighters:rows}:{};
}

/** The one script a freighter runs, from a fixed template: the circuit is its only variable. */
export function script(circuit:Circuit,at=new Date().toISOString()):string {
  return `/** Generated from routes at ${at}: lap_net ${circuit.lap_net}, ${circuit.lap_jumps} jumps a lap.
 * Rewritten by assign(); an edit here is lost. */
import {lap,type Freighter} from 'play/freighter';

const CIRCUIT=${JSON.stringify(circuit,null,2)} as const;

export default async function main(f:Freighter) {
  while(!f.recalled()) {
    const r=await lap(f,CIRCUIT);
    if(r.park)return r;
  }
  return f.park('recalled');
}
`;
}
/** The pilot file's boundary and policy, and one import only: `play/freighter`. */
export function gate(path:string):string[] {
  const source=readFileSync(path,'utf8');
  return [...checkBoundary(source,path).errors,...checkPolicy(source,path,true).errors,
    ...specifiers(source).filter(spec=>spec!=='play/freighter')
      .map(spec=>`${path}: imports ${JSON.stringify(spec)}; a freighter script imports only 'play/freighter'`)];
}

interface Loop {account:Account;recall:boolean;stopping:boolean}
const loops=new Map<string,Loop>();
export const flying=(name:string)=>loops.has(name);

/** Log `name` in on its own account and run its script, detached. Null when it is off; else why
 * not, and the entry is parked with that why. */
export function start(runtime:string,name:string):string|null {
  if(loops.has(name))return `${name} is already flying`;
  const entry=readFleet(runtime)[name];
  if(!entry)return `no freighter named ${name} is assigned`;
  const refused=(why:string)=>{update(runtime,name,{state:'parked',why});return why;};
  const path=scriptPath(runtime,name),login=credentialsPath(runtime,name);
  if(!existsSync(login))return refused(`no login at ${login}: the operator puts a Username:/Password: file there`);
  let who:{username:string;password:string};
  try {who=readCredentials(login);} catch(error) {return refused(message(error));}
  const errors=existsSync(path)?gate(path):[`${path}: missing`];
  if(errors.length)return refused(errors.join('; '));
  let unlock:()=>void;
  try {unlock=controllerLock(join(runtime,`controller-${sha(who.username).slice(0,16)}.lock`));}
  catch(error) {return refused(`${who.username} is held by another live controller (${message(error)})`);}
  pilotHome(runtime);
  const credentials=()=>({kind:'login' as const,...who});
  const account=new Account({url:GAME_WS_URL,reconnect:true,credentials,fastMutationTimeoutMs:60_000});
  const loop:Loop={account,recall:entry.state==='recalling',stopping:false};
  loops.set(name,loop);
  // Gone for good: the session was taken, or the lib gave up. Every later read and command says so.
  let gone:Error|undefined;
  account.onDisconnected(error=>{gone=new Error(`session_replaced or disconnected: ${error.message}`);});
  const live:ReadinessAccount={get state(){return account.state as GameState;},
    refresh:async()=>{if(gone)throw gone;return account.refresh();}};
  const command:ReadinessCommand=async(action,params)=>{
    if(gone)throw gone;
    const [tool,verb]=action.split('/');
    try {
      const reply=await account.send(tool!,verb!,params);
      journalCommand(runtime,`${name}:${action}`,params,true,reply);
      return reply;
    } catch(error) {
      journalCommand(runtime,`${name}:${action}`,params,false,error);
      throw error;
    }
  };
  const f:Freighter={name,account:live,command,owner:entry.owner,float:entry.float,...entry.holding?{holding:entry.holding}:{},
    recalled:()=>loop.recall||loop.stopping,
    // A bridge shutting down stops every loop; the entry stays `running` so the next one resumes it.
    park:why=>{if(!loop.stopping)update(runtime,name,{state:'parked',why});journalRun(runtime,{freighter:name,parked:why},'freighter');
      return {park:why,net:0};},
    report:fields=>{
      const now=readFleet(runtime)[name];
      if(!now)return;
      const {deposited,lapped,...rest}=fields;
      update(runtime,name,{...rest,...deposited?{returned:now.returned+deposited}:{},
        ...lapped===undefined?{}:{lap:now.lap+1,last_lap_net:lapped}});
      journalRun(runtime,{freighter:name,...fields},'freighter');
    }};
  void (async()=>{
    // A login that fails (the server down, the network out) is tried again each minute.
    for(;;) {
      try {await account.connect();await account.authenticate(credentials());break;}
      catch(error) {
        if(loop.stopping||loop.recall||gone)throw error;
        f.report({why:`login failed (${message(error)}); again in a minute`});
        await new Promise(resolve=>setTimeout(resolve,RETRY_MS));
      }
    }
    const url=`${pathToFileURL(path).href}?v=${sha(readFileSync(path)).slice(0,12)}`;
    const loaded=await import(url) as {default?:(f:Freighter)=>Promise<unknown>};
    if(typeof loaded.default!=='function')throw new Error(`${path} exports no default function`);
    await loaded.default(f);
  })().catch(error=>{if(!loop.stopping)update(runtime,name,{state:'parked',why:`the loop broke: ${message(error)}`});})
    .finally(()=>{
      loops.delete(name);unlock();
      try {account.close();} catch {/* never connected */}
    });
  return null;
}

/** Ask `name` home. It finishes the stop it is on, deposits, and parks docked with its cargo. */
export function recallLoop(runtime:string,name:string):string|null {
  const entry=readFleet(runtime)[name];
  if(!entry)return `no freighter named ${name} is assigned`;
  const loop=loops.get(name);
  if(loop){loop.recall=true;update(runtime,name,{state:'recalling'});}
  else if(entry.state!=='parked')update(runtime,name,{state:'parked',why:'recalled'});
  return null;
}

/** After a bridge restart: every `running` freighter flies again, every `recalling` one is parked. */
export function resumeFreighters(runtime:string):void {
  for(const [name,entry] of Object.entries(readFleet(runtime))) {
    if(entry.state==='recalling')update(runtime,name,{state:'parked',why:'recalled'});
    if(entry.state!=='running')continue;
    const why=start(runtime,name);
    if(why)console.error(`freighter ${name} not resumed: ${why}`);
  }
}
/** The bridge is going: close every freighter's account and leave its entry as it is. */
export function stopFreighters():void {
  for(const loop of loops.values()) {
    loop.stopping=true;
    try {loop.account.close();} catch {/* never connected */}
  }
}
