/** Where freighters fly from: the pilot's own bridge process, one extra `Account` per freighter.
 * A freighter has no bridge, juncture or pilot record of its own. Its whole state is a row of
 * `freighters.json` in the pilot's runtime dir, its script is `freighters/<name>.ts` (generated by
 * `assign`), and its login is `freighters/<name>.txt`, which the operator puts there.
 *
 * A loop never touches the play runtime singleton: it commands through its own account, and
 * journals into the pilot's journal under a `<name>:` prefix. When its ring drains it re-plans
 * with `search`, the planner `routes()` is, on its own connection and this runtime's files. Not reachable from a pilot file
 * (`play/freighter` resolves to `index.ts`, never here). */
import {Account,ConnectionClosedError,type FactionQueryTradeIntelResponse,type GameState,type MarketListingItem,type ViewMarketResponse} from '@spacemolt/lib';
import {createHash} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {controllerLock} from '../../controller-lock.ts';
import {GAME_WS_URL,readCredentials} from '../../credentials.ts';
import {miningInventory} from '../../mining-inventory.ts';
import type {ReadinessAccount,ReadinessCommand} from '../../readiness.ts';
import {details} from '../../response-details.ts';
import {journalCommand,journalRun} from '../../run-record.ts';
import {pilotHome} from '../../run.ts';
import {checkBoundary,specifiers} from '../boundary.ts';
import {checkPolicy} from '../policy.ts';
import {knownBooks,rememberBook} from '../market.ts';
import {buysOf,ledgerItems,REST_TICKS,search,type Circuit,type Seat} from '../trading/trading.ts';
import {markMobile,markPlace,readPlaces} from '../places.ts';
import {candidates,explore,target,type Candidate} from '../trading/scout.ts';
import {markDrained,ring} from './drained.ts';
import {claims as carried,dropped,freeTarget,scoutHop,type Approach,type Claim,type Freighter,type Holding,type Known,type Market} from './index.ts';

/** One freighter as `freighters.json` keeps it. */
export interface Entry {
  /** `running` flies (and is resumed after a restart); `scouting` has no circuit that qualifies and
   * flies to read the nearest unknown or stale books (`candidates`), re-planning after each; `waiting`
   * has none and nothing left to scout, docked, re-planning every `REPLAN_TICKS` (both resumed so after
   * a restart); `recalling` finishes its stop; `parked` is stopped for good. */
  state:'running'|'waiting'|'scouting'|'recalling'|'parked';
  circuit:Circuit;float:number;owner:string;
  /** Laps completed since it was assigned, the base it is at or was last at, its wallet there. */
  lap:number;stop?:string;credits?:number;
  /** Credits deposited home to `owner`, all told. */
  returned:number;
  /** The last whole lap's net, against `circuit.lap_net` predicted: the wallet's change plus the
   * change in `holding`. */
  last_lap_net?:number;
  /** The cargo aboard it bought, at cost, after its last stop. */
  holding?:Holding;
  /** Its last flight onto the circuit from where its loop started, kept out of every lap's net. */
  approach?:Approach;
  /** Why it parked, or what fell short at the last stop. */
  why?:string;
  /** Scheduled to stop at the end of the lap it is on (`recall(name, {after:'lap'})`): it parks
   * then and is not re-planned. `assign` clears it. */
  stop_after_lap?:true;
  /** Its auto-reassigns, all told, and the last one's ring and predicted lap_net. */
  reassigned?:{count:number;ring:string;lap_net:number};
  /** Every stow of cargo no circuit stop sold, oldest first: what, at what cost, where, whose storage. */
  stowed?:string[];
  /** Books it read scouting while it waited for a circuit, all told. */
  scouted?:number;
  at:string;
}
/** A freighter as `freighters()` and the menu report it. */
export interface FreighterRow {name:string;state:Entry['state'];lap:number;stop:string|null;credits:number|null;
  returned:number;last_lap_net:number|null;lap_net:number;holding:Holding;approach?:Approach;why?:string;
  stop_after_lap?:true;reassigned?:Entry['reassigned'];stowed?:string[];scouted?:number}

const FILE='freighters.json',RETRY_MS=60_000,TICK_MS=10_000;
/** ponytail: the wait before a failed reconnect is tried again, doubling from RECONNECT_MS to at most
 * RECONNECT_MAX_MS; and how long one reconnect (or the lib's own) may take before it is given up on. */
export const RECONNECT_MS=1_000,RECONNECT_MAX_MS=300_000,RECONNECT_WAIT_MS=60_000;
/** A freighter with no circuit that qualifies re-plans this often: a quarter of the rest a drained ring takes. */
export const REPLAN_TICKS=REST_TICKS/4;
const STOPPED='stopped after its lap, as scheduled';
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
const sha=(text:string|Buffer)=>createHash('sha256').update(text).digest('hex');

export const scriptPath=(runtime:string,name:string)=>join(runtime,'freighters',`${name}.ts`);
export const credentialsPath=(runtime:string,name:string)=>join(runtime,'freighters',`${name}.txt`);

export function readFleet(runtime:string):Record<string,Entry> {
  try {const fleet=JSON.parse(readFileSync(join(runtime,FILE),'utf8'));return fleet&&typeof fleet==='object'?fleet:{};}
  catch {return {};}
}
/** Temp file then rename: a torn write would resume a freighter on a lie. */
export function writeFleet(runtime:string,fleet:Record<string,Entry>):void {
  const path=join(runtime,FILE),temp=`${path}.${process.pid}.tmp`;
  writeFileSync(temp,JSON.stringify(fleet,null,2),{mode:0o600});
  renameSync(temp,path);
}
function update(runtime:string,name:string,fields:Partial<Entry>):void {
  const fleet=readFleet(runtime);
  if(!fleet[name])return;
  fleet[name]={...fleet[name],...fields,at:new Date().toISOString()};
  writeFleet(runtime,fleet);
}

export const row=(name:string,entry:Entry):FreighterRow=>({name,state:entry.state,lap:entry.lap,stop:entry.stop??null,
  credits:entry.credits??null,returned:entry.returned,last_lap_net:entry.last_lap_net??null,lap_net:entry.circuit.lap_net,
  holding:entry.holding??{},...entry.approach?{approach:entry.approach}:{},...entry.why?{why:entry.why}:{},
  ...entry.stop_after_lap?{stop_after_lap:true as const}:{},...entry.reassigned?{reassigned:entry.reassigned}:{},...entry.stowed?.length?{stowed:entry.stowed}:{},...entry.scouted?{scouted:entry.scouted}:{}});
/** `holding` in words: `40 copper_piping (1148 cr)`. */
export const held=(holding:Holding)=>Object.entries(holding).map(([item,row])=>`${row.quantity} ${item} (${Math.round(row.cost)} cr)`).join(', ');
/** The menu's `freighters` rows; nothing when none was ever assigned. */
export function fleetBrief(runtime:string):{freighters?:FreighterRow[]} {
  const rows=Object.entries(readFleet(runtime)).map(([name,entry])=>row(name,entry));
  return rows.length?{freighters:rows}:{};
}

/** The one script a freighter runs, from a fixed template: the circuit is its only variable. */
export function script(circuit:Circuit,at=new Date().toISOString()):string {
  return `/** Generated from routes at ${at}: lap_net ${circuit.lap_net}, ${circuit.lap_jumps} jumps a lap.
 * Rewritten by assign(); an edit here is lost. */
import {lap,type Freighter} from 'play/freighter';

const CIRCUIT=${JSON.stringify(circuit,null,2)} as const;

export default async function main(f:Freighter) {
  while(!f.recalled()) {
    const r=await lap(f,CIRCUIT);
    if(r.park)return r;
  }
  return f.park('recalled');
}
`;
}
/** The pilot file's boundary and policy, and one import only: `play/freighter`. */
export function gate(path:string):string[] {
  const source=readFileSync(path,'utf8');
  return [...checkBoundary(source,path).errors,...checkPolicy(source,path,true).errors,
    ...specifiers(source).filter(spec=>spec!=='play/freighter')
      .map(spec=>`${path}: imports ${JSON.stringify(spec)}; a freighter script imports only 'play/freighter'`)];
}

/** Write `circuit` as `name`'s script and entry, running: only the fields a circuit has (a one-`buy`
 * stop written as `buys`), the gate run on the script, `returned`, `holding` and `reassigned` kept,
 * a stop-after-lap cleared. What `assign` and an auto-reassign both install through. Why it was
 * refused, or null. */
export function install(runtime:string,name:string,circuit:Circuit,fields:{float:number;owner:string;reassigned?:Entry['reassigned']}):string|null {
  const {scope}=circuit;
  const clean:Circuit={closed:true,hold:circuit.hold,lap_jumps:circuit.lap_jumps,lap_net:circuit.lap_net,
    stops:circuit.stops.map(stop=>({at:stop.at,system_id:stop.system_id,buys:buysOf(stop).map(({item,qty,max_price})=>({item,qty,max_price})),
      sell:stop.sell.map(({item,min_price})=>({item,min_price}))})),
    ...scope?{scope:{maxStops:scope.maxStops,maxLegJumps:scope.maxLegJumps,maxJumps:scope.maxJumps}}:{}};
  const path=scriptPath(runtime,name);
  mkdirSync(dirname(path),{recursive:true});
  writeFileSync(path,script(clean));
  const errors=gate(path);
  if(errors.length)return errors.join('; ');
  const fleet=readFleet(runtime),was=fleet[name],reassigned=fields.reassigned??was?.reassigned;
  // The cargo aboard stays aboard, and keeps what it cost.
  fleet[name]={state:'running',circuit:clean,float:fields.float,owner:fields.owner,lap:0,returned:was?.returned??0,
    ...was?.holding?{holding:was.holding}:{},...reassigned?{reassigned}:{},...was?.stowed?{stowed:was.stowed}:{},...was?.scouted?{scouted:was.scouted}:{},at:new Date().toISOString()};
  writeFleet(runtime,fleet);
  return null;
}

/** A flying freighter's switches: `recall` parks it after its stop, `afterLap` after its lap
 * (`lapDone` once that lap has ended), `stopping` is the bridge going. */
interface Loop {recall:boolean;afterLap:boolean;lapDone:boolean;stopping:boolean;close():void}
const loops=new Map<string,Loop>();
export const flying=(name:string)=>loops.has(name);

/** ponytail: how long one base's book, fetched for one freighter, serves every freighter of this
 * process before it is fetched again: a minute, so N freighters on a ring cost one ledger query a
 * base a minute, not one a stop each. Tunable. */
export const BOOK_TTL_MS=60_000;
/** The host's books, by owner runtime and base: the ledger's and the owner's memory's as fetched (at most once a
 * `BOOK_TTL_MS`), and the last live read by any freighter here. */
const fetched=new Map<string,{at:number;book:Promise<Known|undefined>}>(),seen=new Map<string,Known>();
let latest=0;
/** Each flying freighter's claims (by runtime and name): what it carries, to the stop that sells it. */
const claimed=new Map<string,Claim[]>();
const fresher=(a:Known|undefined,b:Known|undefined)=>!a||b&&b.tick>=a.tick?b:a;
/** One base's book off the faction ledger (`query_trade_intel` by `base_id`: its whole book in one
 * call), or the owner's memory, whichever is fresher. Undefined when neither has it. */
async function fetchBook(runtime:string,command:ReadinessCommand,base_id:string):Promise<Known|undefined> {
  const memory=knownBooks(runtime).find(book=>book.base_id===base_id);
  let filed:Known|undefined;
  try {
    const entry=(details(await command('spacemolt_intel/query_trade_intel',{base_id})) as FactionQueryTradeIntelResponse).entries?.find(row=>row.base_id===base_id);
    if(entry)filed={tick:entry.submitted_at_tick,items:ledgerItems(entry)};
  } catch {/* no faction, or no ledger: the memory stands */}
  // An untagged memory is as old as can be: it sizes nothing.
  return fresher(filed,memory&&{tick:memory.tick??0,items:memory.items});
}
/** The books and claims `name`'s loop shares with every other freighter this process flies. */
export function market(runtime:string,name:string,command:ReadinessCommand):Market {
  const key=join(runtime,name);
  return {
    book:async base_id=>{
      const at=join(runtime,base_id);
      let hit=fetched.get(at);
      if(!hit||Date.now()-hit.at>=BOOK_TTL_MS)fetched.set(at,hit={at:Date.now(),book:fetchBook(runtime,command,base_id)});
      return fresher(await hit.book,seen.get(at));
    },
    saw:(base_id,known)=>{seen.set(join(runtime,base_id),known);latest=Math.max(latest,known.tick);},
    tick:()=>latest,
    claimed:(base_id,item_id)=>[...claimed].filter(([who])=>who!==key)
      .reduce((sum,[,rows])=>sum+rows.filter(row=>row.base_id===base_id&&row.item_id===item_id).reduce((part,row)=>part+row.quantity,0),0),
    claim:rows=>{claimed.set(key,rows);},
  };
}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

/** Log `name` in on its own account and run its loop, detached. Null when it is off; else why
 * not, and the entry is parked with that why. */
export function start(runtime:string,name:string):string|null {
  if(loops.has(name))return `${name} is already flying`;
  const entry=readFleet(runtime)[name];
  if(!entry)return `no freighter named ${name} is assigned`;
  const refused=(why:string)=>{update(runtime,name,{state:'parked',why});return why;};
  const path=scriptPath(runtime,name),login=credentialsPath(runtime,name);
  if(!existsSync(login))return refused(`no login at ${login}: the operator puts a Username:/Password: file there`);
  let who:{username:string;password:string};
  try {who=readCredentials(login);} catch(error) {return refused(message(error));}
  const errors=existsSync(path)?gate(path):[`${path}: missing`];
  if(errors.length)return refused(errors.join('; '));
  let unlock:()=>void;
  try {unlock=controllerLock(join(runtime,`controller-${sha(who.username).slice(0,16)}.lock`));}
  catch(error) {return refused(`${who.username} is held by another live controller (${message(error)})`);}
  const credentials=()=>({kind:'login' as const,...who});
  const account=new Account({url:GAME_WS_URL,reconnect:true,credentials,fastMutationTimeoutMs:60_000});
  const {reconnect,gone}=mender(account);
  const live:ReadinessAccount={get state(){return account.state as GameState;},
    refresh:async()=>{const error=gone();if(error)throw error;return account.refresh();}};
  const command:ReadinessCommand=async(action,params)=>{
    const error=gone();if(error)throw error;
    const [tool,verb]=action.split('/');
    try {
      const reply=await account.send(tool!,verb!,params);
      journalCommand(runtime,`${name}:${action}`,params,true,reply,name);
      return reply;
    } catch(error) {
      journalCommand(runtime,`${name}:${action}`,params,false,error,name);
      throw error;
    }
  };
  void launch(runtime,name,live,command,{unlock,close:()=>account.close(),reconnect,
    // A login that fails (the server down, the network out) is tried again each minute.
    login:async loop=>{
      for(;;) {
        try {await account.connect();await account.authenticate(credentials());return;}
        catch(error) {
          if(loop.stopping||loop.recall||gone())throw error;
          update(runtime,name,{why:`login failed (${message(error)}); again in a minute`});
          await sleep(RETRY_MS);
        }
      }
    }});
  return null;
}

/** Reconnects for `account` that never log in twice, and `gone()`: the error once the session is
 * taken for good. A socket can die without closing (live 2026-09-26: each command then hung ~16 minutes
 * until the OS gave up on it), and the lib's own reconnect only starts at a close. So: the lib's
 * reconnect if it is under way or done; else the stale socket is cut loose (its late close, or a 4001
 * when the new login supersedes it, would reach the lib as the current one's, start the lib's own
 * reconnect on top of ours, and a second login would kick ours: live 2026-09-26, a parked "session
 * taken elsewhere" nobody else took) and a fresh socket and login forced in place. The lib reports a
 * close it will not reconnect through (4001/4002) by `onDisconnected`; that parks only when the
 * current connection fails a status read too. */
export function mender(account:Account) {
  // ponytail: reaches into the lib's privates; a lib reconnectOnce that detaches the old socket would replace this.
  const lib=account as unknown as {reconnecting:boolean;_authenticated:boolean;
    socket:{onClose?:unknown;onFrame?:unknown};correlator:{rejectAll(error:Error):void}};
  let gone:Error|undefined;
  account.onDisconnected(error=>{
    account.refresh().catch(()=>{gone??=new Error(`session_replaced or disconnected: ${error.message}`);});
  });
  const bounded=<T>(work:Promise<T>)=>{
    let timer:NodeJS.Timeout|undefined;
    return Promise.race([work,new Promise<never>((_,reject)=>{
      timer=setTimeout(()=>reject(new Error(`no reconnect in ${RECONNECT_WAIT_MS/1000}s`)),RECONNECT_WAIT_MS);timer.unref?.();
    })]).finally(()=>clearTimeout(timer));
  };
  const reconnect=async(error:unknown)=>{
    if(gone)throw gone;
    if(error instanceof ConnectionClosedError||lib.reconnecting) {
      if(account.authenticated&&!lib.reconnecting)return;
      let off=()=>{};
      const back=await bounded(new Promise<void>(resolve=>{off=account.onReconnected(resolve);})).then(()=>true,()=>false).finally(()=>off());
      if(back)return;
      if(lib.reconnecting)throw new Error('the lib is still reconnecting');
    }
    if(gone)throw gone;
    // What the lib does at a close, minus its reconnect and its onDisconnected.
    lib.socket.onClose=undefined;lib.socket.onFrame=undefined;
    lib._authenticated=false;
    lib.correlator.rejectAll(new ConnectionClosedError('socket replaced by a reconnect'));
    await bounded(account.reconnectOnce());
  };
  return {reconnect,gone:()=>gone};
}

/** Run `name`'s loop on `account`, logged in by `login`: its script lap after lap, re-planned when
 * its ring drains. Resolves once it has stopped; the entry says how. What `start` runs detached. */
export function launch(runtime:string,name:string,account:ReadinessAccount,command:ReadinessCommand,
  opts:{login?:(loop:Loop)=>Promise<void>;close?:()=>void;unlock?:()=>void;reconnect?:(error:unknown)=>Promise<void>}={}):Promise<void> {
  const entry=readFleet(runtime)[name];
  const loop:Loop={recall:entry?.state==='recalling',afterLap:entry?.stop_after_lap===true,lapDone:false,stopping:false,close:opts.close??(()=>{})};
  loops.set(name,loop);
  // A lost connection is reconnected here, once for every command in flight, with capped backoff until
  // it is back (or the loop is recalled or stopping); then the error goes on up, and the stop that saw
  // it is redone from a fresh read. Never re-sent: a jump or a buy may have landed.
  let healing:Promise<void>|undefined;
  const heal=(error:unknown)=>healing??=(async()=>{
    for(let n=0;!loop.stopping&&!loop.recall;n++) {
      try {await opts.reconnect!(error);return;}
      catch(failed) {
        if(/^session_replaced or disconnected/.test(message(failed)))return;
        const ms=Math.min(RECONNECT_MS*2**n,RECONNECT_MAX_MS);
        update(runtime,name,{why:`connection lost (${message(error)}); reconnect failed (${message(failed)}); again in ${ms/1000}s`});
        journalRun(runtime,{freighter:name,reconnect_failed:message(failed),again_ms:ms},'freighter');
        await sleep(ms);
      }
    }
  })().finally(()=>{healing=undefined;});
  const mended=async<T>(work:()=>Promise<T>):Promise<T>=>{
    try {return await work();}
    catch(error) {if(opts.reconnect&&dropped(error))await heal(error);throw error;}
  };
  const raw=account,send=command;
  account={get state(){return raw.state;},refresh:()=>mended(()=>raw.refresh())};
  command=(action,params)=>mended(()=>send(action,params));
  // Claims rebuilt from the entry as it resumes: its holding, to the stop that sells each item from the lap's start.
  if(entry)market(runtime,name,command).claim(carried(entry.circuit,0,Object.fromEntries(Object.entries(entry.holding??{}).map(([item,lot])=>[item,lot.quantity]))));
  pilotHome(runtime);
  return (async()=>{
    await opts.login?.(loop);
    let waiting=entry?.state==='waiting'||entry?.state==='scouting';
    // A loop that breaks is launched again, never left for a human: after a lost connection (already
    // reconnected by `mended`) in a minute, after anything else every REPLAN_TICKS.
    // A session taken elsewhere stays parked: another login owns the account.
    for(;;) {
      try {
        for(;;) {
          if(!waiting&&!await run(runtime,name,account,command,loop))return;
          waiting=false;
          if(!await replan(runtime,name,account,command,loop))return;
        }
      } catch(error) {
        if(loop.stopping||/^session_replaced or disconnected/.test(message(error)))throw error;
        // Its state is left as it was, so a bridge restart in the wait resumes it too.
        const ms=dropped(error)?RETRY_MS:REPLAN_TICKS*TICK_MS;
        update(runtime,name,{why:`the loop broke: ${message(error)}; again in ${ms/60_000} minute(s)`});
        journalRun(runtime,{freighter:name,loop_broke:message(error),again_ms:ms},'freighter');
        for(let waited=0;waited<ms&&!loop.recall&&!loop.afterLap&&!loop.stopping;waited+=RETRY_MS)await sleep(RETRY_MS);
        if(loop.stopping)return;
        if(loop.recall||loop.afterLap){update(runtime,name,{state:'parked',why:loop.recall?'recalled':STOPPED});return;}
        const now=readFleet(runtime)[name]?.state;
        waiting=now==='waiting'||now==='scouting';
      }
    }
  })().catch(error=>{if(!loop.stopping)update(runtime,name,{state:'parked',why:`the loop broke: ${message(error)}`});})
    .finally(()=>{
      loops.delete(name);opts.unlock?.();
      // Parked, it carries nothing anywhere: its claims go.
      claimed.delete(join(runtime,name));
      try {loop.close();} catch {/* never connected */}
    });
}

/** What `name` says, into its entry and the journal: a lap's stop and a scouting hop alike. */
function reporter(runtime:string,name:string,account:ReadinessAccount,loop:Loop):Freighter['report'] {
  return fields=>{
    const now=readFleet(runtime)[name];
    if(!now)return;
    // `cleared` is journalled, not kept: the holding after the stop says what is left. `stowed`
    // is kept, all of them, so the owner can find the cargo in storage.
    const {deposited,lapped,cleared:_,stowed,moved,...rest}=fields;
    // A base found moved is mobile: planned from a live find_route from now on, never from a kept place.
    if(moved){markMobile(runtime,moved.at);if(moved.system_id)markPlace(runtime,moved.at,moved.system_id);}
    // A lap ended with a stop after it scheduled: the script's next recalled() is true.
    if(lapped!==undefined&&loop.afterLap)loop.lapDone=true;
    // Arrived at a stop: where it is is a place the owner's routes() need not look up again.
    const at=account.state.location;
    if(fields.stop&&at?.docked_at===fields.stop)markPlace(runtime,fields.stop,at.system_id??'');
    update(runtime,name,{...rest,...deposited?{returned:now.returned+deposited}:{},
      ...lapped===undefined?{}:{lap:now.lap+1,last_lap_net:lapped},...stowed?{stowed:[...now.stowed??[],stowed]}:{}});
    journalRun(runtime,{freighter:name,...fields},'freighter');
  };
}

/** Run the script `name` has now, once, on a fresh `Freighter`. True when it parked for a re-plan:
 * its ring drained, or its hold is full of cargo the circuit never sells that storage refused, and neither a recall nor
 * a stop after the lap was asked for. */
async function run(runtime:string,name:string,account:ReadinessAccount,command:ReadinessCommand,loop:Loop):Promise<boolean> {
  const entry=readFleet(runtime)[name];
  if(!entry)return false;
  let again=false;
  const f:Freighter={name,account,command,owner:entry.owner,float:entry.float,...entry.holding?{holding:entry.holding}:{},
    market:market(runtime,name,command),
    recalled:()=>loop.recall||loop.stopping||loop.lapDone,
    // A bridge shutting down stops every loop; the entry stays as it is so the next one resumes it.
    park:(why,drained,blocked)=>{
      if(why==='recalled'&&loop.lapDone&&!loop.recall)why=STOPPED;
      again=(drained!==undefined||blocked===true)&&!loop.recall&&!loop.afterLap&&!loop.stopping;
      // Waiting, not parked, until the re-plan says: a restart in between resumes the re-plan.
      if(!loop.stopping)update(runtime,name,{state:again?'waiting':'parked',why});
      if(drained!==undefined)markDrained(runtime,ring(entry.circuit.stops),drained);
      journalRun(runtime,{freighter:name,parked:why,...drained===undefined?{}:{drained}},'freighter');
      return {park:why,net:0};},
    report:reporter(runtime,name,account,loop)};
  const path=scriptPath(runtime,name);
  const url=`${pathToFileURL(path).href}?v=${sha(readFileSync(path)).slice(0,12)}`;
  const loaded=await import(url) as {default?:(f:Freighter)=>Promise<unknown>};
  if(typeof loaded.default!=='function')throw new Error(`${path} exports no default function`);
  await loaded.default(f);
  return again;
}

/** After a park for a re-plan: `routes({circuit:{hold}, ...circuit.scope})`, the one planner, read on
 * the freighter's own connection and the owner's runtime files (never the play runtime), then the
 * top circuit installed at its float. True when it has a new circuit to fly. With none, a hold full
 * of cargo the circuit never sells stays parked, its why as it was; any other park scouts: one hop
 * at a time to the nearest `candidates` row (within `SCOUT_JUMPS`) not yet tried this wait, its book
 * read, filed and remembered, the system's bases listed, then re-planned. A system flown to for its
 * bases is left for a base, and with none left to read it flies back to where it last docked. With
 * nothing to scout it waits docked, re-planning every `REPLAN_TICKS`. A recall or a stop after the
 * lap ends it after the hop it is on (or between a failing hop's tries).
 * ponytail: no police or threat gate on a hop: `get_map` carries no police level, and `get_system`
 * only answers once there. Gate on `ClientSystemInfo.police_level` from `explore` if a scout is lost.
 * A blocked park is a hold the lap could neither sell at cost nor stow to `FREE_HOLD` free (`lap`
 * stows what no stop sells to there), so only when both deposits were refused.
 * ponytail: circuits are planned from an empty hold, so a blocked hold takes the first row that sells
 * any of its cargo, and there seldom is one; preferring a ring through a base whose remembered bid
 * covers the leftover's cost (or planning lap 1 from the cargo aboard) is the upgrade. */
async function replan(runtime:string,name:string,account:ReadinessAccount,command:ReadinessCommand,loop:Loop):Promise<boolean> {
  const seat:Seat={account,command,runtime,stop:()=>{if(loop.stopping)throw new Error('the bridge is stopping');},
    book:async()=>{
      const reply=details(await command('spacemolt_market/view_market',{})) as ViewMarketResponse;
      return {items:new Map<string,MarketListingItem>((reply.items??[]).map(row=>[row.item_id,row])),tick:Number(reply.current_tick??0)};
    }};
  // Candidates flown to this wait: each once, so a wait scouts a finite list and then sits docked.
  const tried=new Set<string>(),shared=market(runtime,name,command);
  for(;;) {
    const entry=readFleet(runtime)[name];
    if(!entry||loop.stopping)return false;
    if(loop.recall||loop.afterLap){update(runtime,name,{state:'parked',why:loop.recall?'recalled':STOPPED});return false;}
    await account.refresh();
    const cargo=miningInventory(account.state),ship=account.state.ship,fleet=readFleet(runtime);
    // A ring another freighter here flies is its: two on one ring split its bids.
    const flown=new Set(Object.entries(fleet).filter(([other,row])=>other!==name&&row.state==='running').map(([,row])=>ring(row.circuit.stops)));
    const blocked=(ship?.cargo_capacity??0)-(ship?.cargo_used??0)<freeTarget(ship)&&Object.keys(cargo).length>0
      &&Object.keys(cargo).every(item=>!entry.circuit.stops.some(stop=>stop.sell.some(sale=>sale.item===item)));
    let why:string;
    try {
      const found=await search(seat,{circuit:{hold:entry.circuit.hold},...entry.circuit.scope});
      const rows=found.detail.routes.flatMap(row=>row.circuit??[]).filter(circuit=>!flown.has(ring(circuit.stops)));
      const next=blocked?rows.find(circuit=>circuit.stops.some(stop=>stop.sell.some(sale=>cargo[sale.item]))):rows[0];
      why=(found.why??found.did)+(flown.size?`; passed over the ring(s) another freighter here flies: ${[...flown].join('; ')}`:'');
      if(next) {
        const reassigned={count:(entry.reassigned?.count??0)+1,ring:ring(next.stops),lap_net:next.lap_net};
        const refused=install(runtime,name,next,{float:entry.float,owner:entry.owner,reassigned});
        if(!refused) {
          journalRun(runtime,{freighter:name,reassigned,from:ring(entry.circuit.stops),after:entry.why},'freighter');
          return true;
        }
        why=refused;
      }
    } catch(error) {
      if(/^session_replaced or disconnected/.test(message(error)))throw error;
      why=message(error);
    }
    if(blocked) {
      update(runtime,name,{state:'parked'});
      journalRun(runtime,{freighter:name,not_reassigned:`no circuit sells the cargo aboard: ${why}`},'freighter');
      return false;
    }
    // Nothing qualifies: read the nearest book nobody has read lately, then re-plan on it.
    const docked=account.state.location?.docked_at;
    let list:Candidate[]=[];
    try {list=await candidates(seat,docked?(await seat.book()).tick:shared.tick());}
    catch(error) {if(/^session_replaced or disconnected/.test(message(error)))throw error;}
    // Undocked, only a base: a system flown to for its bases is left for one, never for another system.
    const next=list.find(row=>!tried.has(target(row))&&(docked||row.base_id));
    if(next||!docked) {
      // Scouting ends docked: a system with no base in it, and nothing more to read, flies back to where it last docked.
      const to=next??(entry.stop?{kind:'stale' as const,base_id:entry.stop,system_id:readPlaces(runtime)[entry.stop]??'',jumps:0}:undefined);
      if(!to){update(runtime,name,{state:'parked',why:`scouting left it undocked with no base to return to: ${why}`});return false;}
      tried.add(target(to));
      update(runtime,name,{state:'scouting',why:next?`scouting ${target(to)} (${to.kind}, ${to.jumps} jump(s) away); no circuit qualifies: ${why}`
        :`scouting done, back to ${target(to)}; no circuit qualifies: ${why}`});
      journalRun(runtime,{freighter:name,scouting:to},'freighter');
      const f:Freighter={name,account,command,owner:entry.owner,float:entry.float,...entry.holding?{holding:entry.holding}:{},market:shared,
        recalled:()=>loop.recall||loop.afterLap||loop.stopping,park:why=>({park:why,net:0}),report:reporter(runtime,name,account,loop)};
      const hop=await scoutHop(f,{...to.base_id?{at:to.base_id}:{},system_id:to.system_id});
      // Remembered as the owner's own read: the next re-plan, and the owner's routes(), plan on it.
      if(hop.read)rememberBook(runtime,to.base_id!,account.state.location?.system_id,hop.read.items,hop.read.tick);
      let bases:string[]=[];
      if(!hop.why)try {bases=await explore(command,runtime);} catch {/* unlisted: the system is scouted again another wait */}
      if(hop.read&&next)update(runtime,name,{scouted:(readFleet(runtime)[name]?.scouted??0)+1});
      journalRun(runtime,{freighter:name,scouted:target(to),...hop.read?{tick:hop.read.tick}:{},...hop.why?{why:hop.why}:{},...bases.length?{bases}:{}},'freighter');
      if(!next&&hop.why){update(runtime,name,{state:'parked',why:`scouting left it undocked: ${target(to)}: ${hop.why}`});return false;}
      continue;
    }
    update(runtime,name,{state:'waiting',why:`waiting for a circuit: ${why}`});
    journalRun(runtime,{freighter:name,waiting:why},'freighter');
    for(let waited=0;waited<REPLAN_TICKS*TICK_MS&&!loop.recall&&!loop.afterLap&&!loop.stopping;waited+=RETRY_MS)await sleep(RETRY_MS);
  }
}

/** Ask `name` home. It finishes the stop it is on, deposits, and parks docked with its cargo. With
 * `after:'lap'`, it finishes the lap it is on instead, selling as usual. Either way it is not re-planned. */
export function recallLoop(runtime:string,name:string,after?:'lap'):string|null {
  const entry=readFleet(runtime)[name];
  if(!entry)return `no freighter named ${name} is assigned`;
  const loop=loops.get(name);
  if(loop&&after==='lap'){loop.afterLap=true;update(runtime,name,{stop_after_lap:true});}
  else if(loop){loop.recall=true;update(runtime,name,{state:'recalling'});}
  else if(entry.state!=='parked')update(runtime,name,{state:'parked',why:after?STOPPED:'recalled'});
  return null;
}

/** After a bridge restart: every `running` or `waiting` freighter flies again, every `recalling` one is parked. */
export function resumeFreighters(runtime:string):void {
  for(const [name,entry] of Object.entries(readFleet(runtime))) {
    if(entry.state==='recalling')update(runtime,name,{state:'parked',why:'recalled'});
    if(entry.state!=='running'&&entry.state!=='waiting'&&entry.state!=='scouting')continue;
    const why=start(runtime,name);
    if(why)console.error(`freighter ${name} not resumed: ${why}`);
  }
}
/** The bridge is going: close every freighter's account and leave its entry as it is. */
export function stopFreighters():void {
  for(const loop of loops.values()) {
    loop.stopping=true;
    try {loop.close();} catch {/* never connected */}
  }
}
