/** Where freighters fly from: the pilot's own bridge process, one extra `Account` per freighter.
 * A freighter has no bridge, juncture or pilot record of its own. Its whole state is a row of
 * `freighters.json` in the pilot's runtime dir, its script is `freighters/<name>.ts` (generated by
 * `assign`), and its login is `freighters/<name>.txt`, which the operator puts there.
 *
 * A loop never touches the play runtime singleton: it commands through its own account, and
 * journals into the pilot's journal under a `<name>:` prefix. When its ring drains it re-plans
 * with `search`, the planner `routes()` is, on its own connection and this runtime's files. Not reachable from a pilot file
 * (`play/freighter` resolves to `index.ts`, never here). */
import {Account,ConnectionClosedError} from '@spacemolt/lib';
import {Effect,Exit,Option,Result,Schema,Struct} from 'effect';
import {createHash} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {controllerLock} from '../../controller-lock.ts';
import {GAME_WS_URL,readCredentials} from '../../credentials.ts';
import {miningInventory} from '../../mining-inventory.ts';
import type {ReadinessAccount,ReadinessCommand} from '../../readiness.ts';
import {journalCommand,journalConnection,journalRun} from '../../run-record.ts';
import {pilotHome} from '../../run.ts';
import {listing,words} from '../../servicing.ts';
import {replyBody,rows} from '../../storage.ts';
import {checkBoundary,specifiers} from '../boundary.ts';
import {checkPolicy} from '../policy.ts';
import {knownBooks,rememberBook} from '../market.ts';
import {inFaction} from '../../trade-intel.ts';
import {Game,GameLive,SeamFailed,field,rawError} from '../game.ts';
import {num} from '../rows.ts';
import {Stopped} from '../runtime.ts';
import {buysOf,LedgerEntry,ledgerItems,REST_TICKS,searchEffect,type Circuit,type Seat} from '../trading/trading.ts';
import {markMobile,markPlace,readPlaces} from '../places.ts';
import {candidatesEffect,exploreEffect,target,type Candidate} from '../trading/scout.ts';
import {markDrained,ring} from './drained.ts';
import {scoutHop,scoutHopEffect} from './lap.ts';
import {claims as carried,dropped,freeTarget,type Approach,type Claim,type Freighter,type Holding,type Known,type Market} from './index.ts';

/** One freighter as `freighters.json` keeps it. */
export interface Entry {
  /** `running` flies (and is resumed after a restart); `scouting` has no circuit that qualifies and
   * flies to read the nearest unknown or stale books (`candidates`), re-planning after each; `waiting`
   * has none and nothing left to scout, docked, re-planning every `REPLAN_TICKS` (both resumed so after
   * a restart); `recalling` finishes its stop; `parked` is stopped for good. */
  state:'running'|'waiting'|'scouting'|'recalling'|'parked';
  circuit:Circuit;float:number;owner:string;
  /** Laps completed since it was assigned, the base it is at or was last at, its wallet there. */
  lap:number;stop?:string;credits?:number;
  /** Credits deposited home to `owner`, all told. */
  returned:number;
  /** The last whole lap's net, against `circuit.lap_net` predicted: the wallet's change plus the
   * change in `holding`. */
  last_lap_net?:number;
  /** The cargo aboard it bought, at cost, after its last stop. */
  holding?:Holding;
  /** Its last flight onto the circuit from where its loop started, kept out of every lap's net. */
  approach?:Approach;
  /** Why it parked, or what fell short at the last stop. */
  why?:string|undefined;
  /** Scheduled to stop at the end of the lap it is on (`recall(name, {after:'lap'})`): it parks
   * then and is not re-planned. `assign` clears it. */
  stop_after_lap?:true;
  /** Its auto-reassigns, all told, and the last one's ring and predicted lap_net. */
  reassigned?:{count:number;ring:string;lap_net:number};
  /** Every stow of cargo no circuit stop sold, oldest first: what, at what cost, where, whose storage. */
  stowed?:string[];
  /** Books it read scouting while it waited for a circuit, all told. */
  scouted?:number;
  at:string;
}
/** A freighter as `freighters()` and the menu report it. */
export interface FreighterRow {name:string;state:Entry['state'];lap:number;stop:string|null;credits:number|null;
  returned:number;last_lap_net:number|null;lap_net:number;holding:Holding;approach?:Approach;why?:string;
  stop_after_lap?:true;reassigned?:Entry['reassigned'];stowed?:string[];scouted?:number}

const FILE='freighters.json',RETRY_MS=60_000,TICK_MS=10_000;
/** ponytail: the wait before a failed reconnect is tried again, doubling from RECONNECT_MS to at most
 * RECONNECT_MAX_MS; and how long one reconnect (or the lib's own) may take before it is given up on. */
export const RECONNECT_MS=1_000,RECONNECT_MAX_MS=300_000,RECONNECT_WAIT_MS=60_000;
/** A freighter with no circuit that qualifies re-plans this often: a quarter of the rest a drained ring takes. */
export const REPLAN_TICKS=REST_TICKS/4;
const STOPPED='stopped after its lap, as scheduled';
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
const sha=(text:string|Buffer)=>createHash('sha256').update(text).digest('hex');

export const scriptPath=(runtime:string,name:string)=>join(runtime,'freighters',`${name}.ts`);
export const credentialsPath=(runtime:string,name:string)=>join(runtime,'freighters',`${name}.txt`);

const STATES=new Set<string>(['running','waiting','scouting','recalling','parked']);
/** A row of `freighters.json` the host can fly: a known state and a circuit with stops. Written only by this file, so the
 * rest of the shape is trusted; a row that fails this is not flown (a half-written one always crashed on use), said
 * once, and kept on disk by `writeFleet`. */
const unflyable=(row:unknown)=>!STATES.has(String(field(row,'state')))?'no known state':!Array.isArray(field(field(row,'circuit'),'stops'))?'no circuit stops':undefined;
const isEntry=(row:unknown):row is Entry=>unflyable(row)===undefined;
const decodeFleet=Schema.decodeUnknownOption(Schema.fromJsonString(Schema.Record(Schema.String,Schema.Unknown)));
/** Every row on disk, flyable or not; undefined when there is no file, null when it is not a JSON object. */
function fleetOnDisk(runtime:string):Record<string,unknown>|null|undefined {
  let text:string;
  try {text=readFileSync(join(runtime,FILE),'utf8');}
  catch {return undefined;} // edge: no fleet file yet is no freighter assigned
  const fleet=decodeFleet(text);
  return Option.isSome(fleet)?fleet.value:null;
}
/** Rows already said unreadable, so a fleet read every re-plan says each once a process. */
const unreadSaid=new Set<string>();
export function readFleet(runtime:string):Record<string,Entry> {
  return Object.fromEntries(Object.entries(fleetOnDisk(runtime)??{}).filter((pair):pair is [string,Entry]=>{
    const why=unflyable(pair[1]),said=JSON.stringify([runtime,...pair]);
    if(why&&!unreadSaid.has(said)){unreadSaid.add(said);journalRun(runtime,{freighter:pair[0],fleet_row_unread:why},'freighter');}
    return why===undefined;
  }));
}
/** Temp file then rename: a torn write would resume a freighter on a lie. A row the host cannot read is written back as
 * it was, and a file that is not a JSON object is set aside first: a freighter's record (its float, its
 * holding) is never erased because a read could not decode it. */
export function writeFleet(runtime:string,fleet:Record<string,Entry>):void {
  const path=join(runtime,FILE),temp=`${path}.${process.pid}.tmp`,was=fleetOnDisk(runtime);
  if(was===null) {
    const aside=`${path}.unreadable-${new Date().toISOString().replace(/[:.]/g,'-')}`;
    renameSync(path,aside);
    journalRun(runtime,{set_aside:aside},'fleet_unreadable');
  }
  const out:Record<string,unknown>={};
  for(const [name,row] of Object.entries(was??{}))if(!isEntry(row))out[name]=row;
  writeFileSync(temp,JSON.stringify({...out,...fleet},null,2),{mode:0o600});
  renameSync(temp,path);
}
function update(runtime:string,name:string,fields:Partial<Entry>):void {
  const fleet=readFleet(runtime);
  if(!fleet[name])return;
  fleet[name]={...fleet[name],...fields,at:new Date().toISOString()};
  writeFleet(runtime,fleet);
}

export const row=(name:string,entry:Entry):FreighterRow=>({name,state:entry.state,lap:entry.lap,stop:entry.stop??null,
  credits:entry.credits??null,returned:entry.returned,last_lap_net:entry.last_lap_net??null,lap_net:entry.circuit.lap_net,
  holding:entry.holding??{},...entry.approach?{approach:entry.approach}:{},...entry.why?{why:entry.why}:{},
  ...entry.stop_after_lap?{stop_after_lap:true as const}:{},...entry.reassigned?{reassigned:entry.reassigned}:{},...entry.stowed?.length?{stowed:entry.stowed}:{},...entry.scouted?{scouted:entry.scouted}:{}});
/** `holding` in words: `40 copper_piping (1148 cr)`. */
export const held=(holding:Holding)=>Object.entries(holding).map(([item,row])=>`${row.quantity} ${item} (${Math.round(row.cost)} cr)`).join(', ');
/** The menu's `freighters` rows; nothing when none was ever assigned. */
export function fleetBrief(runtime:string):{freighters?:FreighterRow[]} {
  const rows=Object.entries(readFleet(runtime)).map(([name,entry])=>row(name,entry));
  return rows.length?{freighters:rows}:{};
}

/** The one script a freighter runs, from a fixed template: the circuit is its only variable. */
export function script(circuit:Circuit,at=new Date().toISOString()):string {
  return `/** Generated from routes at ${at}: lap_net ${circuit.lap_net}, ${circuit.lap_jumps} jumps a lap.
 * Rewritten by assign(); an edit here is lost. */
import {lap,type Freighter} from 'play/freighter';

const CIRCUIT=${JSON.stringify(circuit,null,2)} as const;

export default async function main(f:Freighter) {
  while(!f.recalled()) {
    const r=await lap(f,CIRCUIT);
    if(r.park)return r;
  }
  return f.park('recalled');
}
`;
}
/** The pilot file's boundary and policy, and one import only: `play/freighter`. */
export function gate(path:string):string[] {
  const source=readFileSync(path,'utf8');
  return [...checkBoundary(source,path).errors,...checkPolicy(source,path,true).errors,
    ...specifiers(source).filter(spec=>spec!=='play/freighter')
      .map(spec=>`${path}: imports ${JSON.stringify(spec)}; a freighter script imports only 'play/freighter'`)];
}

/** Write `circuit` as `name`'s script and entry, running: only the fields a circuit has (a one-`buy`
 * stop written as `buys`), the gate run on the script, `returned`, `holding` and `reassigned` kept,
 * a stop-after-lap cleared. What `assign` and an auto-reassign both install through. Why it was
 * refused, or null. */
export function install(runtime:string,name:string,circuit:Circuit,fields:{float:number;owner:string;reassigned?:Entry['reassigned']}):string|null {
  const {scope}=circuit;
  const clean:Circuit={closed:true,hold:circuit.hold,lap_jumps:circuit.lap_jumps,lap_net:circuit.lap_net,
    stops:circuit.stops.map(stop=>({at:stop.at,system_id:stop.system_id,buys:buysOf(stop).map(({item,qty,max_price})=>({item,qty,max_price})),
      sell:stop.sell.map(({item,min_price})=>({item,min_price}))})),
    ...scope?{scope:{...scope.maxStops===undefined?{}:{maxStops:scope.maxStops},...scope.maxLegJumps===undefined?{}:{maxLegJumps:scope.maxLegJumps},...scope.maxJumps===undefined?{}:{maxJumps:scope.maxJumps}}}:{}};
  const path=scriptPath(runtime,name);
  mkdirSync(dirname(path),{recursive:true});
  writeFileSync(path,script(clean));
  const errors=gate(path);
  if(errors.length)return errors.join('; ');
  const fleet=readFleet(runtime),was=fleet[name],reassigned=fields.reassigned??was?.reassigned;
  // The cargo aboard stays aboard, and keeps what it cost.
  fleet[name]={state:'running',circuit:clean,float:fields.float,owner:fields.owner,lap:0,returned:was?.returned??0,
    ...was?.holding?{holding:was.holding}:{},...reassigned?{reassigned}:{},...was?.stowed?{stowed:was.stowed}:{},...was?.scouted?{scouted:was.scouted}:{},at:new Date().toISOString()};
  writeFleet(runtime,fleet);
  return null;
}

/** A flying freighter's switches: `recall` parks it after its stop, `afterLap` after its lap
 * (`lapDone` once that lap has ended), `stopping` is the bridge going. */
interface Loop {recall:boolean;afterLap:boolean;lapDone:boolean;stopping:boolean;close():void}
const loops=new Map<string,Loop>();
export const flying=(name:string)=>loops.has(name);

/** ponytail: how long one base's book, fetched for one freighter, serves every freighter of this
 * process before it is fetched again: a minute, so N freighters on a ring cost one ledger query a
 * base a minute, not one a stop each. Tunable. */
export const BOOK_TTL_MS=60_000;
/** The host's books, by owner runtime and base: the ledger's and the owner's memory's as fetched (at most once a
 * `BOOK_TTL_MS`), and the last live read by any freighter here. */
const fetched=new Map<string,{at:number;name:string;book:Promise<Result.Result<Known|undefined,SeamFailed>>}>(),seen=new Map<string,Known>();
let latest=0;
/** Each flying freighter's claims (by runtime and name): what it carries, to the stop that sells it. */
const claimed=new Map<string,Claim[]>();
const fresher=(a:Known|undefined,b:Known|undefined)=>!a||b&&b.tick>=a.tick?b:a;
/** One base's book off the faction ledger (`query_trade_intel` by `base_id`: its whole book in one
 * call), or the owner's memory, whichever is fresher. Undefined when neither has it. */
const fetchBook=(runtime:string,name:string,account:object,base_id:string)=>Effect.gen(function*() {
  const memory=knownBooks(runtime).find(book=>book.base_id===base_id);
  let filed:Known|undefined;
  if(inFaction(account,text=>journalRun(runtime,{freighter:name,text},'faction_skipped'))) {
    const asked=yield* Effect.result((yield* Game).command('spacemolt_intel/query_trade_intel',{base_id}));
    // No faction, or no ledger: the memory stands, and the developers are told why.
    if(Result.isFailure(asked))journalRun(runtime,{freighter:name,base_id,ledger_unread:words(asked.failure)},'freighter');
    else {
      const row=rows(field(replyBody(asked.success),'entries')).find(entry=>field(entry,'base_id')===base_id),entry=row===undefined?Option.none():decodeLedger(row);
      if(Option.isSome(entry))filed={tick:entry.value.submitted_at_tick,items:ledgerItems(entry.value)};
      else if(row!==undefined)journalRun(runtime,{freighter:name,base_id,ledger_unread:'the entry does not decode',row},'freighter');
    }
  }
  // An untagged memory is as old as can be: it sizes nothing.
  return fresher(filed,memory&&{tick:memory.tick??0,items:memory.items});
});
/** The fields `fetchBook` reads of the base's ledger entry, as the ledger reader decodes them (the live `system_id` is not one). */
const decodeLedger=Schema.decodeUnknownOption(LedgerEntry.mapFields(Struct.pick(['submitted_at_tick','items'])));
/** The books and claims `name`'s loop shares with every other freighter this process flies. */
export function market(runtime:string,name:string,account:object,command:ReadinessCommand):Market {
  const key=join(runtime,name);
  return {
    book:async base_id=>{
      const at=join(runtime,base_id),own=()=>settle(()=>fly(fetchBook(runtime,name,account,base_id),command));
      let hit=fetched.get(at);
      if(!hit||Date.now()-hit.at>=BOOK_TTL_MS)fetched.set(at,hit={at:Date.now(),name,book:own()});
      let got=await hit.book;
      // Another freighter's failed fetch (its session taken, a bug on its connection) is its own: this one asks for itself.
      if(Result.isFailure(got)&&hit.name!==name)got=await own();
      if(Result.isSuccess(got))return fresher(got.success,seen.get(at));
      if(fetched.get(at)===hit)fetched.delete(at);
      throw got.failure.cause;
    },
    saw:(base_id,known)=>{seen.set(join(runtime,base_id),known);latest=Math.max(latest,known.tick);},
    tick:()=>latest,
    claimed:(base_id,item_id)=>[...claimed].filter(([who])=>who!==key)
      .reduce((sum,[,rows])=>sum+rows.filter(row=>row.base_id===base_id&&row.item_id===item_id).reduce((part,row)=>part+row.quantity,0),0),
    claim:rows=>{claimed.set(key,rows);},
  };
}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
/** The host's edge: an Effect on this freighter's own `Game` (its mended command and account, never the play runtime's).
 * What it did not hand back as a value goes up as the raw error, a session taken elsewhere or a bug, for the loop's own handler. */
async function fly<A,E>(effect:Effect.Effect<A,E,Game>,command:ReadinessCommand,account?:ReadinessAccount):Promise<A> {
  const exit=await Effect.runPromiseExit(effect.pipe(Effect.provide(GameLive({send:command,...account?{refresh:()=>account.refresh()}:{}}))));
  if(Exit.isSuccess(exit))return exit.value;
  throw rawError(exit.cause);
}
/** A Promise settled to a value: its rejection is the `SeamFailed` it was, never swallowed here. */
const settle=<T>(work:()=>Promise<T>)=>new Promise<T>(resolve=>resolve(work())).then(value=>Result.succeed(value),cause=>Result.fail(new SeamFailed({cause})));
/** Close a freighter's account. */
function shut(loop:Loop):void {
  try {loop.close();}
  catch {/* never connected */} // edge: the lib's close throws on an account that never connected; nothing to release
}

/** Log `name` in on its own account and run its loop, detached. Null when it is off; else why
 * not, and the entry is parked with that why. */
export function start(runtime:string,name:string):string|null {
  if(loops.has(name))return `${name} is already flying`;
  const entry=readFleet(runtime)[name];
  if(!entry)return `no freighter named ${name} is assigned`;
  const refused=(why:string)=>{update(runtime,name,{state:'parked',why});return why;};
  const path=scriptPath(runtime,name),login=credentialsPath(runtime,name);
  if(!existsSync(login))return refused(`no login at ${login}: the operator puts a Username:/Password: file there`);
  const read=Result.try({try:()=>readCredentials(login),catch:message});
  if(Result.isFailure(read))return refused(read.failure);
  const who=read.success;
  const errors=existsSync(path)?gate(path):[`${path}: missing`];
  if(errors.length)return refused(errors.join('; '));
  const locked=Result.try({try:()=>controllerLock(join(runtime,`controller-${sha(who.username).slice(0,16)}.lock`)),catch:message});
  if(Result.isFailure(locked))return refused(`${who.username} is held by another live controller (${locked.failure})`);
  const unlock=locked.success;
  const credentials=()=>({kind:'login' as const,...who});
  const account=new Account({url:GAME_WS_URL,reconnect:true,credentials,fastMutationTimeoutMs:60_000});
  const {reconnect,gone}=mender(account);
  journalConnection(runtime,account,name);
  const live:ReadinessAccount={get state(){return account.state;},
    refresh:async()=>{const error=gone();if(error)throw error;return account.refresh();}};
  const command:ReadinessCommand=async(action,params)=>{
    const error=gone();if(error)throw error;
    const [tool='',verb='']=action.split('/');
    const since=Date.now();
    return account.send(tool,verb,params).then(reply=>{
      journalCommand(runtime,`${name}:${action}`,params,true,reply,{freighter:name,ms:Date.now()-since});
      return reply;
    },error=>{
      journalCommand(runtime,`${name}:${action}`,params,false,error,{freighter:name,ms:Date.now()-since});
      throw error;
    });
  };
  void launch(runtime,name,live,command,{unlock,close:()=>account.close(),reconnect,
    // A login that fails (the server down, the network out) is tried again each minute.
    login:async loop=>{
      for(;;) {
        const tried=await settle(async()=>{await account.connect();await account.authenticate(credentials());});
        if(Result.isSuccess(tried))return;
        const error=tried.failure.cause;
        if(loop.stopping||loop.recall||gone())throw error;
        update(runtime,name,{why:`login failed (${message(error)}); again in a minute`});
        await sleep(RETRY_MS);
      }
    }});
  return null;
}

/** Reconnects for `account` that never log in twice, and `gone()`: the error once the session is
 * taken for good. A socket can die without closing (live 2026-09-26: each command then hung ~16 minutes
 * until the OS gave up on it), and the lib's own reconnect only starts at a close. So: the lib's
 * reconnect if it is under way or done; else the stale socket is cut loose (its late close, or a 4001
 * when the new login supersedes it, would reach the lib as the current one's, start the lib's own
 * reconnect on top of ours, and a second login would kick ours: live 2026-09-26, a parked "session
 * taken elsewhere" nobody else took) and a fresh socket and login forced in place. The lib reports a
 * close it will not reconnect through (4001/4002) by `onDisconnected`; that parks only when the
 * current connection fails a status read too. */
export function mender(account:Account) {
  // ponytail: reaches into the lib's privates; a lib reconnectOnce that detaches the old socket would replace this.
  const lib=(key:string)=>Reflect.get(account,key);
  let gone:Error|undefined;
  account.onDisconnected(error=>{
    void settle(()=>account.refresh()).then(read=>{if(Result.isFailure(read))gone??=new Error(`session_replaced or disconnected: ${error.message}`);});
  });
  const bounded=<T>(work:Promise<T>)=>{
    let timer:NodeJS.Timeout|undefined;
    return Promise.race([work,new Promise<never>((_,reject)=>{
      timer=setTimeout(()=>reject(new Error(`no reconnect in ${RECONNECT_WAIT_MS/1000}s`)),RECONNECT_WAIT_MS);timer.unref?.();
    })]).finally(()=>clearTimeout(timer));
  };
  const reconnect=async(error:unknown)=>{
    if(gone)throw gone;
    if(error instanceof ConnectionClosedError||lib('reconnecting')) {
      if(account.authenticated&&!lib('reconnecting'))return;
      let off=()=>{};
      const back=await bounded(new Promise<void>(resolve=>{off=account.onReconnected(resolve);})).then(()=>true,()=>false).finally(()=>off());
      if(back)return;
      if(lib('reconnecting'))throw new Error('the lib is still reconnecting');
    }
    if(gone)throw gone;
    // What the lib does at a close, minus its reconnect and its onDisconnected.
    Reflect.set(lib('socket'),'onClose',undefined);Reflect.set(lib('socket'),'onFrame',undefined);
    Reflect.set(account,'_authenticated',false);
    Reflect.apply(Reflect.get(lib('correlator'),'rejectAll'),lib('correlator'),[new ConnectionClosedError('socket replaced by a reconnect')]);
    await bounded(account.reconnectOnce());
  };
  return {reconnect,gone:()=>gone};
}

/** Run `name`'s loop on `account`, logged in by `login`: its script lap after lap, re-planned when
 * its ring drains. Resolves once it has stopped; the entry says how. What `start` runs detached. */
export function launch(runtime:string,name:string,account:ReadinessAccount,command:ReadinessCommand,
  opts:{login?:(loop:Loop)=>Promise<void>;close?:()=>void;unlock?:()=>void;reconnect?:(error:unknown)=>Promise<void>}={}):Promise<void> {
  const entry=readFleet(runtime)[name];
  const loop:Loop={recall:entry?.state==='recalling',afterLap:entry?.stop_after_lap===true,lapDone:false,stopping:false,close:opts.close??(()=>{})};
  loops.set(name,loop);
  // A lost connection is reconnected here, once for every command in flight, with capped backoff until
  // it is back (or the loop is recalled or stopping); then the error goes on up, and the stop that saw
  // it is redone from a fresh read. Never re-sent: a jump or a buy may have landed.
  let healing:Promise<void>|undefined;
  const heal=(error:unknown)=>healing??=(async()=>{
    const reconnect=opts.reconnect;
    for(let n=0;reconnect&&!loop.stopping&&!loop.recall;n++) {
      const mended=await settle(()=>reconnect(error));
      if(Result.isSuccess(mended))return;
      const failed=mended.failure.cause;
      if(/^session_replaced or disconnected/.test(message(failed)))return;
      const ms=Math.min(RECONNECT_MS*2**n,RECONNECT_MAX_MS);
      update(runtime,name,{why:`connection lost (${message(error)}); reconnect failed (${message(failed)}); again in ${ms/1000}s`});
      journalRun(runtime,{freighter:name,reconnect_failed:message(failed),again_ms:ms},'freighter');
      await sleep(ms);
    }
  })().finally(()=>{healing=undefined;});
  const mended=async<T>(work:()=>Promise<T>):Promise<T>=>{
    const done=await settle(work);
    if(Result.isSuccess(done))return done.success;
    const error=done.failure.cause;
    if(opts.reconnect&&dropped(error))await heal(error);
    throw error;
  };
  const raw=account,send=command;
  account={get state(){return raw.state;},refresh:()=>mended(()=>raw.refresh())};
  command=(action,params)=>mended(()=>send(action,params));
  // Claims rebuilt from the entry as it resumes: its holding, to the stop that sells each item from the lap's start.
  if(entry)market(runtime,name,account,command).claim(carried(entry.circuit,0,Object.fromEntries(Object.entries(entry.holding??{}).map(([item,lot])=>[item,lot.quantity]))));
  pilotHome(runtime);
  return settle(async()=>{
    await opts.login?.(loop);
    let waiting=entry?.state==='waiting'||entry?.state==='scouting';
    // A loop that breaks is launched again, never left for a human: after a lost connection (already
    // reconnected by `mended`) in a minute, after anything else every REPLAN_TICKS.
    // A session taken elsewhere stays parked: another login owns the account.
    for(;;) {
      const flew=await settle(async()=>{
        for(;;) {
          if(!waiting&&!await run(runtime,name,account,command,loop))return;
          waiting=false;
          if(!await replan(runtime,name,account,command,loop))return;
        }
      });
      if(Result.isSuccess(flew))return;
      const error=flew.failure.cause;
      if(loop.stopping||/^session_replaced or disconnected/.test(message(error)))throw error;
      // Its state is left as it was, so a bridge restart in the wait resumes it too.
      const ms=dropped(error)?RETRY_MS:REPLAN_TICKS*TICK_MS;
      update(runtime,name,{why:`the loop broke: ${message(error)}; again in ${ms/60_000} minute(s)`});
      journalRun(runtime,{freighter:name,loop_broke:message(error),again_ms:ms},'freighter');
      for(let waited=0;waited<ms&&!loop.recall&&!loop.afterLap&&!loop.stopping;waited+=RETRY_MS)await sleep(RETRY_MS);
      if(loop.stopping)return;
      if(loop.recall||loop.afterLap){update(runtime,name,{state:'parked',why:loop.recall?'recalled':STOPPED});return;}
      const now=readFleet(runtime)[name]?.state;
      waiting=now==='waiting'||now==='scouting';
    }
  }).then(ended=>{if(Result.isFailure(ended)&&!loop.stopping)update(runtime,name,{state:'parked',why:`the loop broke: ${message(ended.failure.cause)}`});})
    .finally(()=>{
      loops.delete(name);opts.unlock?.();
      // Parked, it carries nothing anywhere: its claims go.
      claimed.delete(join(runtime,name));
      shut(loop);
    });
}

/** What `name` says, into its entry and the journal: a lap's stop and a scouting hop alike. */
function reporter(runtime:string,name:string,account:ReadinessAccount,loop:Loop):Freighter['report'] {
  return fields=>{
    const now=readFleet(runtime)[name];
    if(!now)return;
    // `cleared` is journalled, not kept: the holding after the stop says what is left. `stowed`
    // is kept, all of them, so the owner can find the cargo in storage.
    const {deposited,lapped,cleared:_,stowed,moved,...rest}=fields;
    // A base found moved is mobile: planned from a live find_route from now on, never from a kept place.
    if(moved){markMobile(runtime,moved.at);if(moved.system_id)markPlace(runtime,moved.at,moved.system_id);}
    // A lap ended with a stop after it scheduled: the script's next recalled() is true.
    if(lapped!==undefined&&loop.afterLap)loop.lapDone=true;
    // Arrived at a stop: where it is is a place the owner's routes() need not look up again.
    const at=account.state.location;
    if(fields.stop&&at?.docked_at===fields.stop)markPlace(runtime,fields.stop,at.system_id??'');
    update(runtime,name,{...rest,...deposited?{returned:now.returned+deposited}:{},
      ...lapped===undefined?{}:{lap:now.lap+1,last_lap_net:lapped},...stowed?{stowed:[...now.stowed??[],stowed]}:{}});
    journalRun(runtime,{freighter:name,...fields},'freighter');
  };
}

/** Run the script `name` has now, once, on a fresh `Freighter`. True when it parked for a re-plan:
 * its ring drained, or its hold is full of cargo the circuit never sells that storage refused, and neither a recall nor
 * a stop after the lap was asked for. */
async function run(runtime:string,name:string,account:ReadinessAccount,command:ReadinessCommand,loop:Loop):Promise<boolean> {
  const entry=readFleet(runtime)[name];
  if(!entry)return false;
  let again=false;
  const f:Freighter={name,account,command,owner:entry.owner,float:entry.float,...entry.holding?{holding:entry.holding}:{},
    market:market(runtime,name,account,command),
    recalled:()=>loop.recall||loop.stopping||loop.lapDone,
    // A bridge shutting down stops every loop; the entry stays as it is so the next one resumes it.
    park:(why,drained,blocked)=>{
      if(why==='recalled'&&loop.lapDone&&!loop.recall)why=STOPPED;
      again=(drained!==undefined||blocked===true)&&!loop.recall&&!loop.afterLap&&!loop.stopping;
      // Waiting, not parked, until the re-plan says: a restart in between resumes the re-plan.
      if(!loop.stopping)update(runtime,name,{state:again?'waiting':'parked',why});
      if(drained!==undefined)markDrained(runtime,ring(entry.circuit.stops),drained);
      journalRun(runtime,{freighter:name,parked:why,...drained===undefined?{}:{drained}},'freighter');
      return {park:why,net:0};},
    report:reporter(runtime,name,account,loop)};
  const path=scriptPath(runtime,name);
  const url=`${pathToFileURL(path).href}?v=${sha(readFileSync(path)).slice(0,12)}`;
  const loaded:{default?:unknown}=await import(url);
  if(typeof loaded.default!=='function')throw new Error(`${path} exports no default function`);
  await loaded.default(f);
  return again;
}

/** After a park for a re-plan: `routes({circuit:{hold}, ...circuit.scope})`, the one planner, read on
 * the freighter's own connection and the owner's runtime files (never the play runtime), then the
 * top circuit installed at its float. True when it has a new circuit to fly. With none, a hold full
 * of cargo the circuit never sells stays parked, its why as it was; any other park scouts: one hop
 * at a time to the nearest `candidates` row (within `SCOUT_JUMPS`) not yet tried this wait, its book
 * read, filed and remembered, the system's bases listed, then re-planned. A system flown to for its
 * bases is left for a base, and with none left to read it flies back to where it last docked. With
 * nothing to scout it waits docked, re-planning every `REPLAN_TICKS`. A recall or a stop after the
 * lap ends it after the hop it is on (or between a failing hop's tries).
 * ponytail: no police or threat gate on a hop: `get_map` carries no police level, and `get_system`
 * only answers once there. Gate on `ClientSystemInfo.police_level` from `explore` if a scout is lost.
 * A blocked park is a hold the lap could neither sell at cost nor stow to `FREE_HOLD` free (`lap`
 * stows what no stop sells to there), so only when both deposits were refused.
 * ponytail: circuits are planned from an empty hold, so a blocked hold takes the first row that sells
 * any of its cargo, and there seldom is one; preferring a ring through a base whose remembered bid
 * covers the leftover's cost (or planning lap 1 from the cargo aboard) is the upgrade. */
const replan=(runtime:string,name:string,account:ReadinessAccount,command:ReadinessCommand,loop:Loop)=>fly(replanEffect(runtime,name,account,command,loop),command,account);
const replanEffect=(runtime:string,name:string,account:ReadinessAccount,command:ReadinessCommand,loop:Loop)=>Effect.gen(function*() {
  const game=yield* Game;
  const book=Effect.gen(function*() {
    const reply=replyBody(yield* game.command('spacemolt_market/view_market',{}));
    return {items:new Map(rows(field(reply,'items')).flatMap(listing).map(row=>[row.item_id,row])),tick:num(reply,'current_tick')??0};
  });
  // The bridge stopping ends a search as the typed `Stopped`; the loop's own `stopping` is what reads it.
  const seat:Seat={account,command,runtime,freighter:name,stop:()=>{if(loop.stopping)throw new Stopped();},book};
  // Candidates flown to this wait: each once, so a wait scouts a finite list and then sits docked.
  const tried=new Set<string>(),shared=market(runtime,name,account,command);
  for(;;) {
    const entry=readFleet(runtime)[name];
    if(!entry||loop.stopping)return false;
    if(loop.recall||loop.afterLap){update(runtime,name,{state:'parked',why:loop.recall?'recalled':STOPPED});return false;}
    yield* game.refresh;
    const cargo=miningInventory(account.state),ship=account.state.ship,fleet=readFleet(runtime);
    // A ring another freighter here flies is its: two on one ring split its bids.
    const flown=new Set(Object.entries(fleet).filter(([other,row])=>other!==name&&row.state==='running').map(([,row])=>ring(row.circuit.stops)));
    const blocked=(ship?.cargo_capacity??0)-(ship?.cargo_used??0)<freeTarget(ship)&&Object.keys(cargo).length>0
      &&Object.keys(cargo).every(item=>!entry.circuit.stops.some(stop=>stop.sell.some(sale=>sale.item===item)));
    let why:string;
    // A refusal or a lost reply on a read is a why, not a failure; a stop ends the wait; anything else is a bug or a taken session and goes up.
    const searched=yield* Effect.result(searchEffect(seat,{circuit:{hold:entry.circuit.hold},...entry.circuit.scope}));
    if(Result.isFailure(searched)) {
      if(searched.failure instanceof Stopped)return false;
      why=words(searched.failure);
    } else {
      const found=searched.success;
      const rows=found.detail.routes.flatMap(row=>row.circuit??[]).filter(circuit=>!flown.has(ring(circuit.stops)));
      const next=blocked?rows.find(circuit=>circuit.stops.some(stop=>stop.sell.some(sale=>cargo[sale.item]))):rows[0];
      why=(found.why??found.did)+(flown.size?`; passed over the ring(s) another freighter here flies: ${[...flown].join('; ')}`:'');
      if(next) {
        const reassigned={count:(entry.reassigned?.count??0)+1,ring:ring(next.stops),lap_net:next.lap_net};
        const refused=install(runtime,name,next,{float:entry.float,owner:entry.owner,reassigned});
        if(!refused) {
          journalRun(runtime,{freighter:name,reassigned,from:ring(entry.circuit.stops),after:entry.why},'freighter');
          return true;
        }
        why=refused;
      }
    }
    if(blocked) {
      update(runtime,name,{state:'parked'});
      journalRun(runtime,{freighter:name,not_reassigned:`no circuit sells the cargo aboard: ${why}`},'freighter');
      return false;
    }
    // Nothing qualifies: read the nearest book nobody has read lately, then re-plan on it.
    const docked=account.state.location?.docked_at;
    const scouted=yield* Effect.result(Effect.gen(function*() {return yield* candidatesEffect(seat,docked?(yield* book).tick:shared.tick());}));
    let list:Candidate[]=[];
    if(Result.isSuccess(scouted))list=scouted.success;
    else if(scouted.failure instanceof Stopped)return false;
    else journalRun(runtime,{freighter:name,candidates_unread:words(scouted.failure)},'freighter');
    // Undocked, only a base: a system flown to for its bases is left for one, never for another system.
    const next=list.find(row=>!tried.has(target(row))&&(docked||row.base_id));
    if(next||!docked) {
      // Scouting ends docked: a system with no base in it, and nothing more to read, flies back to where it last docked.
      const to=next??(entry.stop?{kind:'stale' as const,base_id:entry.stop,system_id:readPlaces(runtime)[entry.stop]??'',jumps:0}:undefined);
      if(!to){update(runtime,name,{state:'parked',why:`scouting left it undocked with no base to return to: ${why}`});return false;}
      tried.add(target(to));
      update(runtime,name,{state:'scouting',why:next?`scouting ${target(to)} (${to.kind}, ${to.jumps} jump(s) away); no circuit qualifies: ${why}`
        :`scouting done, back to ${target(to)}; no circuit qualifies: ${why}`});
      journalRun(runtime,{freighter:name,scouting:to},'freighter');
      const f:Freighter={name,account,command,owner:entry.owner,float:entry.float,...entry.holding?{holding:entry.holding}:{},market:shared,
        recalled:()=>loop.recall||loop.afterLap||loop.stopping,park:why=>({park:why,net:0}),report:reporter(runtime,name,account,loop)};
      // A session taken elsewhere fails here with the error that said so, and goes up to the loop.
      const hop:Awaited<ReturnType<typeof scoutHop>>=yield* scoutHopEffect(f,{...to.base_id?{at:to.base_id}:{},system_id:to.system_id});
      // Remembered as the owner's own read: the next re-plan, and the owner's routes(), plan on it.
      if(hop.read&&to.base_id)rememberBook(runtime,to.base_id,account.state.location?.system_id,hop.read.items,hop.read.tick);
      let bases:string[]=[];
      if(!hop.why) {
        // Unlisted: the system is scouted again another wait.
        const listed=yield* Effect.result(exploreEffect(seat));
        if(Result.isSuccess(listed))bases=listed.success;
        else if(listed.failure instanceof Stopped)return false;
        else journalRun(runtime,{freighter:name,explore_unread:words(listed.failure)},'freighter');
      }
      if(hop.read&&next)update(runtime,name,{scouted:(readFleet(runtime)[name]?.scouted??0)+1});
      journalRun(runtime,{freighter:name,scouted:target(to),...hop.read?{tick:hop.read.tick}:{},...hop.why?{why:hop.why}:{},...bases.length?{bases}:{}},'freighter');
      if(!next&&hop.why){update(runtime,name,{state:'parked',why:`scouting left it undocked: ${target(to)}: ${hop.why}`});return false;}
      continue;
    }
    update(runtime,name,{state:'waiting',why:`waiting for a circuit: ${why}`});
    journalRun(runtime,{freighter:name,waiting:why},'freighter');
    for(let waited=0;waited<REPLAN_TICKS*TICK_MS&&!loop.recall&&!loop.afterLap&&!loop.stopping;waited+=RETRY_MS)yield* Effect.sleep(RETRY_MS);
  }
});

/** Ask `name` home. It finishes the stop it is on, deposits, and parks docked with its cargo. With
 * `after:'lap'`, it finishes the lap it is on instead, selling as usual. Either way it is not re-planned. */
export function recallLoop(runtime:string,name:string,after?:'lap'):string|null {
  const entry=readFleet(runtime)[name];
  if(!entry)return `no freighter named ${name} is assigned`;
  const loop=loops.get(name);
  if(loop&&after==='lap'){loop.afterLap=true;update(runtime,name,{stop_after_lap:true});}
  else if(loop){loop.recall=true;update(runtime,name,{state:'recalling'});}
  else if(entry.state!=='parked')update(runtime,name,{state:'parked',why:after?STOPPED:'recalled'});
  return null;
}

/** After a bridge restart: every `running` or `waiting` freighter flies again, every `recalling` one is parked. */
export function resumeFreighters(runtime:string):void {
  for(const [name,entry] of Object.entries(readFleet(runtime))) {
    if(entry.state==='recalling')update(runtime,name,{state:'parked',why:'recalled'});
    if(entry.state!=='running'&&entry.state!=='waiting'&&entry.state!=='scouting')continue;
    const why=start(runtime,name);
    if(why)console.error(`freighter ${name} not resumed: ${why}`);
  }
}
/** The bridge is going: close every freighter's account and leave its entry as it is. */
export function stopFreighters():void {
  for(const loop of loops.values()) {
    loop.stopping=true;
    shut(loop);
  }
}
