/** A freighter: a second account that flies one closed circuit over and over, with no pilot of its
 * own. Its script is generated by `assign` and does one thing, `lap(f, CIRCUIT)` until recalled;
 * the host (`host.ts`) logs it in and hands it `f`. Nothing here touches the play runtime: a
 * freighter's commands go through its own account, never the pilot's.
 *
 * Every failure is handled here, once, so the script stays a loop:
 * - a disconnect or any other throw: wait a minute and redo the stop from a fresh read. A stop is
 *   idempotent: sales are sized by what is held, the buy by the free hold and what is already aboard;
 * - the session taken by another connection: park, and never log in again;
 * - a sale or buy the game refuses: say so and go on; three stops in a row with no trade parks it;
 * - a route short of fuel, a blocked flight, no credits for fuel: park, docked where it is;
 * - LOSING_LAPS laps in a row that net 0 or less: park, docked at the lap's last stop.
 * A parked ship keeps its cargo aboard. */
import {SpacemoltError,type MarketListingItem,type OrderLevel,type ViewMarketResponse} from '@spacemolt/lib';
import {miningInventory} from '../../mining-inventory.ts';
import type {ReadinessAccount,ReadinessCommand} from '../../readiness.ts';
import {details} from '../../response-details.ts';
import {ServiceBlocked,serviceShip} from '../../servicing.ts';
import {fileIntel} from '../../trade-intel.ts';
import {FuelRouteShortfall,TravelBlocked,travelTo} from '../../travel.ts';
import type {Circuit} from '../trading/trading.ts';

/** What one lap did: `park` when the freighter stopped for good, and why; `net` the credits it
 * made, deposits home included. */
export interface Lap {park?:string;net:number}
/** What a freighter says as it goes. `deposited` is one deposit home; `lapped` a whole lap's net. */
export interface Report {stop?:string;credits?:number;deposited?:number;lapped?:number;why?:string}
/** What the host hands a freighter's script. */
export interface Freighter {
  name:string;
  /** The freighter's own account and command seam, logged in by the host. */
  account:ReadinessAccount;
  command:ReadinessCommand;
  /** The player its profit goes home to, and the credits it keeps aboard to trade with. */
  owner:string;
  float:number;
  /** True once `recall` asked it home: it finishes the stop it is on and parks. */
  recalled():boolean;
  /** Stop for good with `why`; the Lap to return. */
  park(why:string):Lap;
  report(fields:Report):void;
}
type Stop=Circuit['stops'][number];

/** ponytail: fuel units kept beyond each leg's quote, and credits never spent on cargo so a tank
 * can always be bought. Flat numbers, not the hull's: a Titan burns 7 a jump and fills for
 * ~1600 cr. Tunable. */
const FUEL_RESERVE=10,FUEL_MONEY=2_000;
/** ponytail: the tax a buy is sized against, above the live 250 bps so a buy never overdraws. */
const TAX=0.05;
/** Stops in a row with no trade before the circuit is called dead. */
const DEAD_STOPS=3;
/** ponytail: laps in a row netting 0 or less before the circuit parks as a loser. The first lap
 * starts empty and only buys, so one losing lap is expected; three is the books. A lap that pays
 * but far under `lap_net` flies on: it still makes money. Tunable. */
const LOSING_LAPS=3;
const RETRY_MS=60_000;
const OPEN='an open path would strand a freighter that repeats it; use routes({circuit:{hold}})';

const message=(error:unknown)=>error instanceof Error?error.message:String(error);
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const finite=(value:unknown,min:number)=>typeof value==='number'&&Number.isFinite(value)&&value>=min;

/** Why `circuit` cannot be flown as a repeating lap, or null. The shape alone: `assign` checks the
 * bases against what is known as well. */
export function closure(circuit:Circuit):string|null {
  const stops=Array.isArray(circuit?.stops)?circuit.stops:[];
  const problem=circuit?.closed!==true?'not a closed circuit'
    :stops.some(stop=>typeof stop?.at!=='string'||!stop.at||typeof stop.system_id!=='string'||!stop.system_id||!Array.isArray(stop.sell))
      ?'every stop needs at, system_id and a sell list'
    :new Set(stops.map(stop=>stop.at)).size<2?'fewer than 2 distinct stops'
    :!stops.some(stop=>stop.buy)?'no stop buys anything'
    :stops.find(stop=>stop.buy&&!(finite(stop.buy.qty,1)&&finite(stop.buy.max_price,1)))?'a buy needs a qty and a max_price of at least 1'
    :stops.flatMap(stop=>stop.sell).find(sale=>!finite(sale.min_price,0))?'a sale needs a min_price'
    :stops.flatMap(stop=>stop.sell).find(sale=>!stops.some(stop=>stop.buy?.item===sale.item))
      ?`${stops.flatMap(stop=>stop.sell).find(sale=>!stops.some(stop=>stop.buy?.item===sale.item))!.item} is sold but bought nowhere on the circuit`
    :null;
  return problem&&`${problem}; ${OPEN}`;
}

/** One side of a book row, best first; a row without levels is its top of book. */
const levels=(orders:OrderLevel[]|undefined,price:number,quantity:number):OrderLevel[]=>
  orders?.length?orders:price>0&&quantity>0?[{price_each:price,quantity}]:[];

/** Why a throw ends the circuit, or null when the stop is worth redoing. */
function parked(error:unknown):string|null {
  const text=message(error);
  if(/session_replaced|disconnected/i.test(text)||(error as {code?:unknown})?.code===4001)return 'session taken elsewhere';
  if(error instanceof FuelRouteShortfall)return `fuel shortfall: ${text}`;
  // A quote the world moved under is a race, redone; any other refusal to fly is the route's.
  if(error instanceof TravelBlocked&&!/changed/.test(text))return `travel blocked: ${text}`;
  if(error instanceof ServiceBlocked)return `no credits for fuel: ${text}`;
  return null;
}

/** A game refusal is said and skipped; anything else (a lost connection) is the stop's to redo. */
async function attempt(f:Freighter,at:string,what:string,send:()=>Promise<unknown>):Promise<boolean> {
  try {await send();return true;}
  catch(error) {
    if(!(error instanceof SpacemoltError))throw error;
    f.report({why:`${at}: ${what} refused: ${error.message}`});
    return false;
  }
}

/** One stop: fly there and dock, service, sell the listed items at their floors, buy within the
 * cap, send the credits above the float home. Returns how many trades took. */
async function visit(f:Freighter,stop:Stop,sent:(credits:number)=>void):Promise<number> {
  const {account,command}=f;
  // Tired's service margin is the wallet itself; the reserve is 0, and the fill is checked after. A
  // counter that refuses a service is passed by: the next quote says whether the tank still reaches.
  const service=async()=>{await attempt(f,stop.at,'service',()=>serviceShip(account,command,{mood:'Tired'}));};
  await account.refresh();
  if(account.state.location?.docked_at!==stop.at) {
    const quote=details(await command('spacemolt/find_route',{id:stop.at}));
    await travelTo(account,command,{system_id:stop.system_id,poi_id:String(quote.target_poi??stop.at),base_id:stop.at},
      {reserve:FUEL_RESERVE,maxJumps:null,refuel:service});
  }
  await service();
  f.report({stop:stop.at});
  const market=details(await command('spacemolt_market/view_market',{})) as ViewMarketResponse;
  const book=new Map<string,MarketListingItem>((market.items??[]).map(row=>[row.item_id,row]));
  await fileIntel(account,command,stop.at,market.items??[],Number(market.current_tick??0),why=>f.report({why}));
  let traded=0;
  for(const {item,min_price} of stop.sell) {
    const row=book.get(item),held=miningInventory(account.state)[item]??0;
    // ponytail: the book is read once and the sale sent at market, so a bid pulled in between can
    // fill a unit under the floor. The game takes no limit price on `sell`; a sell order would.
    const n=Math.min(held,(row?levels(row.buy_orders,row.best_buy,row.best_buy_qty):[])
      .filter(level=>level.price_each>=min_price).reduce((sum,level)=>sum+level.quantity,0));
    if(n&&await attempt(f,stop.at,`sell ${n} ${item}`,()=>command('spacemolt/sell',{id:item,quantity:n})))traded++;
  }
  await account.refresh();
  if(stop.buy) {
    const {item,qty,max_price}=stop.buy,row=book.get(item),ship=account.state.ship;
    // ponytail: a unit is one unit of hold. A bulkier item's buy is refused by the game and skipped.
    const want=Math.min(qty-(miningInventory(account.state)[item]??0),(ship?.cargo_capacity??0)-(ship?.cargo_used??0));
    let n=0,budget=(account.state.player?.credits??0)-FUEL_MONEY;
    for(const level of row?levels(row.sell_orders,row.best_sell,row.best_sell_qty):[]) {
      if(level.price_each>max_price||n>=want)break;
      const take=Math.max(0,Math.min(want-n,level.quantity,Math.floor(budget/(level.price_each*(1+TAX)))));
      n+=take;budget-=take*level.price_each*(1+TAX);
      if(take<level.quantity)break;
    }
    if(n>0&&await attempt(f,stop.at,`buy ${n} ${item}`,()=>command('spacemolt/buy',{id:item,quantity:n})))traded++;
    await account.refresh();
  }
  const spare=(account.state.player?.credits??0)-f.float;
  if(spare>0&&await attempt(f,stop.at,`deposit ${spare} cr to ${f.owner}`,
    ()=>command('spacemolt_storage/deposit',{target:f.owner,credits:spare}))) {
    sent(spare);f.report({deposited:spare});
    await account.refresh();
  }
  f.report({credits:account.state.player?.credits??0});
  return traded;
}

/** Stops in a row with no trade, and laps in a row that lost money, across laps. */
const idle=new WeakMap<Freighter,number>(),losing=new WeakMap<Freighter,number>();

/** Fly `circuit` once round, stop by stop, from wherever the freighter is. Never throws: every
 * failure is redone or parks it (see the module note). Ends with the lap's net reported. */
export async function lap(f:Freighter,circuit:Circuit):Promise<Lap> {
  const open=closure(circuit);
  if(open)return f.park(open);
  const opening=f.account.state.player?.credits??0;
  let home=0;
  for(const stop of circuit.stops) {
    let traded:number;
    for(;;) {
      try {traded=await visit(f,stop,credits=>{home+=credits;});break;}
      catch(error) {
        const why=parked(error);
        if(why)return f.park(why);
        f.report({why:`${stop.at}: ${message(error)}; again in a minute`});
        await sleep(RETRY_MS);
        if(f.recalled())return f.park('recalled');
      }
    }
    const dead=traded?0:(idle.get(f)??0)+1;
    idle.set(f,dead);
    if(dead>=DEAD_STOPS)return f.park(`circuit dead: ${dead} stops in a row with no trade`);
    if(f.recalled())return f.park('recalled');
  }
  const net=(f.account.state.player?.credits??0)+home-opening;
  f.report({lapped:net});
  const lost=net>0?0:(losing.get(f)??0)+1;
  losing.set(f,lost);
  if(lost>=LOSING_LAPS)return {...f.park(`${lost} laps lost money: last ${net} vs predicted ${circuit.lap_net}`),net};
  return {net};
}
