/** A freighter: a second account that flies one closed circuit over and over, with no pilot of its
 * own. Its script is generated by `assign` and does one thing, `lap(f, CIRCUIT)` until recalled;
 * the host (`host.ts`) logs it in and hands it `f`. Nothing here touches the play runtime: a
 * freighter's commands go through its own account, never the pilot's.
 *
 * Every failure is handled here, once, so the script stays a loop:
 * - a disconnect or any other throw: wait a minute and redo the stop from a fresh read. A stop is
 *   idempotent: sales are sized by what is held, each buy by the free hold and what is already aboard.
 *   A trade or deposit whose reply is lost is never re-sent: the account re-read says what it moved.
 *   The why it said clears once the stop is reached. STOP_TRIES failed tries in a row skip the stop
 *   for the lap, as a stop with no trade, so no stop can hold a freighter forever. A lost connection
 *   (`dropped`) is not a try: the host reconnects before it reaches here, and the stop is redone;
 * - a base away from the circuit's system for it (a mobile station): each flight goes to the system
 *   `find_route` names for the base now, and the move is reported for the host to record;
 * - the session taken by another connection: park, and never log in again;
 * - cargo it bought that the circuit never sells (left from an old circuit): sold at any stop whose
 *   bid covers its cost a unit, after the stop's own sales and before its buys; never at a loss, and
 *   cargo it never bought (cost unknown) is never sold;
 * - cargo aboard the circuit never sells, bought or not, at a new circuit's first stop or at a lap's
 *   last stop, after the sales and before the buys: stowed there, the cheapest a unit first (never
 *   bought counts as 0), only until `FREE_HOLD` of the hold is free, into the owner's storage
 *   (`deposit` with `target`), else its own; the rest rides along, cleared at cost where a bid covers it;
 * - a sale or buy the game refuses: say so and go on; three stops in a row with no trade parks it,
 *   the ring recorded as drained, unless cargo the circuit never sells, that neither a bid nor a store
 *   took, holds the free hold under `FREE_HOLD`: then the why names that cargo and the ring is not drained;
 * - recalled: it buys nothing more, and parks after the stop it is on;
 * - a route short of fuel, a blocked flight, no credits for fuel: park, docked where it is;
 * - LOSING_LAPS laps in a row that net 0 or less: park, docked at the lap's last stop, the ring drained.
 * With a host's `market` (always, flown from a host), each buy is sized by `plan`, the one planner,
 * against the live book here and the freshest known books of the lap's later stops, and each lap
 * starts by planning the whole lap: one that plans at 0 or less on fresh books parks drained unflown.
 * A parked ship keeps the circuit's cargo aboard, and `holding` says what it cost. A drained or blocked park is
 * the host's to re-plan (`host.ts`); the script only parks. */
import {ConnectionClosedError,type MarketListingItem,type OrderLevel} from '@spacemolt/lib';
import {Cause,Effect,Result} from 'effect';
import {miningInventory} from '../../mining-inventory.ts';
import type {ReadinessAccount,ReadinessCommand} from '../../readiness.ts';
import {ServiceBlocked,listing as readRow,serviceShipEffect} from '../../servicing.ts';
import {rows,replyBody} from '../../storage.ts';
import {fileIntelEffect} from '../../trade-intel.ts';
import {FuelRouteShortfall,TravelBlocked,travelToEffect} from '../../travel.ts';
import {Game,GameLive,field,isGameError,message,rawError,type SeamFailed} from '../game.ts';
import {num} from '../rows.ts';
import {buysOf,plan,type Book,type Circuit,type Listing} from '../trading/trading.ts';

/** What one lap did: `park` when the freighter stopped for good, and why; `net` the credits it
 * made, deposits home included, with the cargo aboard at its cost (see `Holding`). */
export interface Lap {park?:string;net:number}
/** The cargo aboard that the freighter bought, per item: units and what they cost, tax included.
 * A sale takes units off at their average cost; units aboard it never bought are not in it. */
export type Holding=Record<string,{quantity:number;cost:number}>;
/** The flight to a circuit's first stop from wherever the loop started, off the circuit: its jumps
 * and what it cost, fuel and repairs on arrival included. Never part of a lap's net. */
export interface Approach {jumps:number;credits:number}
/** What a freighter says as it goes. `deposited` is one deposit home; `lapped` a whole lap's net;
 * `holding` the cargo aboard at cost, after each stop; `approach` the flight onto the circuit;
 * `cleared` leftover cargo sold at cost or better, e.g. "cleared 98 copper_piping at 36 (cost 29.6)";
 * `stowed` cargo the circuit never sells put in storage, e.g. "98 copper_piping (cost 2898) at
 * nova_terra_central for Chrisjen Avasarala", or "… in its own storage" when the owner's was refused. */
export interface Report {stop?:string;credits?:number;deposited?:number;lapped?:number;holding?:Holding;approach?:Approach;cleared?:string;stowed?:string;why?:string|undefined;
  /** A stop's base found away from the system the circuit kept for it: a mobile station. `system_id`
   * where `find_route` places it now, when known. The host records it mobile and re-places it. */
  moved?:{at:string;system_id?:string}}
/** A base's book as the host knows it: rows, and the game tick it was read or filed on. */
export interface Known {tick:number;items:Listing[]}
/** One freighter's claim on a base's bids: units aboard it carries there to sell. */
export interface Claim {base_id:string;item_id:string;quantity:number}
/** What a host shares between its freighters (`host.ts`): books and depth claims. */
export interface Market {
  /** The freshest book known for `base_id`: the faction ledger's (cached `BOOK_TTL_MS`), a live read
   * by any freighter of the host, or the owner's market memory. Never throws. */
  book(base_id:string):Promise<Known|undefined>;
  /** A live read at `base_id`, kept for every freighter of the host. */
  saw(base_id:string,known:Known):void;
  /** The latest game tick any freighter of the host has read; 0 before any. */
  tick():number;
  /** Units of `item_id` the host's other freighters carry to sell at `base_id`. */
  claimed(base_id:string,item_id:string):number;
  /** This freighter's claims now, replacing its last. */
  claim(rows:Claim[]):void;
}
/** What the host hands a freighter's script. */
export interface Freighter {
  name:string;
  /** The freighter's own account and command seam, logged in by the host. */
  account:ReadinessAccount;
  command:ReadinessCommand;
  /** The player its profit goes home to, and the credits it keeps aboard to trade with. */
  owner:string;
  float:number;
  /** The cargo aboard at cost when it was started, as last reported. */
  holding?:Holding;
  /** True once `recall` asked it home: it finishes the stop it is on and parks. */
  recalled():boolean;
  /** Stop with `why`; the Lap to return. `drained`, the game tick, when the circuit's books ran dry
   * (no trade, or laps that lost money): the host records the ring as resting and re-plans. `blocked`
   * when the hold is full of cargo the circuit never sells: the host re-plans, the ring not drained. */
  park(why:string,drained?:number,blocked?:boolean):Lap;
  report(fields:Report):void;
  /** The host's books and claims. Absent (a bare `lap` in a test), buys are sized by the circuit's caps alone. */
  market?:Market;
}
type Stop=Circuit['stops'][number];

/** ponytail: credits never spent on cargo so a tank can always be bought. A flat number, not
 * the hull's: a Titan fills for ~1600 cr. Tunable. A leg keeps no fuel beyond its quote; the
 * mood's reserve is where Tired begins, and the circuit services at every stop. */
const FUEL_MONEY=2_000;
/** ponytail: the tax a buy is sized against, above the live 250 bps so a buy never overdraws. */
const TAX=0.05;
/** Stops in a row with no trade before the circuit is called dead. */
const DEAD_STOPS=3;
/** ponytail: tries at one stop (a minute apart) before it is skipped for the lap. Any throw counts
 * but a lost connection (`dropped`): an outage is the host's to reconnect through, never a dead
 * stop (live 2026-09-26: an hour of closed sockets skipped every stop and parked the ring). Tunable. */
const STOP_TRIES=3;
/** ponytail: laps in a row netting 0 or less before the circuit parks as a loser. The first lap
 * starts empty and only buys, so one losing lap is expected; three is the books. A lap that pays
 * but far under `lap_net` flies on: it still makes money. Tunable. */
const LOSING_LAPS=3;
/** ponytail: the share of the hold a stow frees, and no more: cargo the circuit never sells is stowed
 * only down to this much free, the rest kept aboard to clear at cost. Operator's call: a big hauler
 * still buys at a profit into 40%. Tunable. */
export const FREE_HOLD=0.4;
/** The free hold a stow aims at: `FREE_HOLD` of the hold, whole units. */
export const freeTarget=(ship:{cargo_capacity?:number}|undefined)=>Math.ceil(FREE_HOLD*(ship?.cargo_capacity??0));
const RETRY_MS=60_000;
/** A later stop's book older than this many ticks (30 minutes at ten seconds a tick) counts at half
 * its depth when a buy is sized: NPC books move rarely, but other traders fill bids. */
export const STALE_TICKS=180;
/** ponytail: past this many ticks (3 hours) a later stop's book justifies no buy for a sale there;
 * the lap visits it, and its fresh read sizes the next lap. Tunable. */
export const IGNORE_TICKS=1080;
const BUILD='use routes({circuit:{hold}})';

const finite=(value:unknown,min:number)=>typeof value==='number'&&Number.isFinite(value)&&value>=min;

/** Why `circuit` cannot be flown as a repeating lap, or null. The shape alone: `assign` checks the
 * bases against what is known as well; a lap needs only each stop's `system_id`, as it reads books live. */
export function closure(circuit:Circuit):string|null {
  const stops=Array.isArray(circuit?.stops)?circuit.stops:[];
  const problem=circuit?.closed!==true?'not a closed circuit: an open path would strand a freighter that repeats it'
    :stops.some(stop=>typeof stop?.at!=='string'||!stop.at||typeof stop.system_id!=='string'||!stop.system_id||!Array.isArray(stop.sell))
      ?'every stop needs at, system_id and a sell list'
    :new Set(stops.map(stop=>stop.at)).size<2?'fewer than 2 distinct stops'
    :!stops.some(stop=>buysOf(stop).length)?'no stop buys anything'
    :stops.flatMap(buysOf).find(buy=>!(typeof buy?.item==='string'&&finite(buy.qty,1)&&finite(buy.max_price,1)))?'a buy needs an item, a qty and a max_price of at least 1'
    :stops.flatMap(stop=>stop.sell).find(sale=>!finite(sale.min_price,0))?'a sale needs a min_price'
    :null;
  const orphan=stops.flatMap(stop=>stop.sell).find(sale=>!stops.flatMap(buysOf).some(buy=>buy.item===sale.item));
  const why=problem??(orphan&&`${orphan.item} is sold but bought nowhere on the circuit`);
  return why?`${why}; ${BUILD}`:null;
}

/** One side of a book row, best first; a row without levels is its top of book. */
const levels=(orders:OrderLevel[]|undefined,price:number,quantity:number):OrderLevel[]=>
  orders?.length?orders:price>0&&quantity>0?[{price_each:price,quantity}]:[];

/** How much of a book `age` ticks old counts: whole, half past `STALE_TICKS`, none past `IGNORE_TICKS` or unknown. */
const share=(age:number|undefined)=>age===undefined||age>IGNORE_TICKS?0:age>STALE_TICKS?0.5:1;
const ageOf=(known:Known|undefined,now:number)=>known&&Math.max(0,now-known.tick);
/** Units `from` to `to` of a side, best first, each level's depth scaled by `part`. */
const units=(side:OrderLevel[],part:number,from:number,to:number):OrderLevel[]=>{
  let at=0;
  return side.flatMap(level=>{
    const n=Math.floor(level.quantity*part),lo=Math.max(at,from),hi=Math.min(at+n,to);
    at+=n;return hi>lo?[{price_each:level.price_each,quantity:hi-lo}]:[];
  });
};
const listing=(item_id:string,bids:OrderLevel[],asks:OrderLevel[]):Listing=>({item_id,best_buy:bids[0]?.price_each??0,
  best_buy_qty:bids[0]?.quantity??0,best_sell:asks[0]?.price_each??0,best_sell_qty:asks[0]?.quantity??0,buy_orders:bids,sell_orders:asks});
/** `stop`'s book as a lap plans it: bids only for what it sells, at or above each floor, less what
 * the host's other freighters carry there; asks only for what it buys, at or under each cap, to
 * `cap(item)` units; the depth weighed by the book's age (`share`). What `plan` sizes a freighter by. */
function planned(f:Freighter,stop:Stop,known:Known|undefined,now:number,cap:(item:string)=>number):Book {
  const age=ageOf(known,now),part=share(age),rows=new Map(known?.items.map(one=>[one.item_id,one]));
  const items=new Map<string,Listing>();
  for(const {item,min_price} of stop.sell) {
    const one=rows.get(item);
    if(one)items.set(item,listing(item,units(levels(one.buy_orders,one.best_buy,one.best_buy_qty).filter(level=>level.price_each>=min_price),
      part,f.market?.claimed(stop.at,item)??0,Infinity),[]));
  }
  for(const {item,max_price} of buysOf(stop)) {
    const one=rows.get(item);
    if(one)items.set(item,listing(item,items.get(item)?.buy_orders??[],
      units(levels(one.sell_orders,one.best_sell,one.best_sell_qty).filter(level=>level.price_each<=max_price),part,0,cap(item))));
  }
  return {base_id:stop.at,source:'faction ledger',age:age??0,items};
}
/** What a later stop's book says of a sale of `item` there, when it cut a buy. */
function heard(f:Freighter,stop:Stop,known:Known|undefined,now:number,item:string):string {
  const age=ageOf(known,now),claimed=f.market?.claimed(stop.at,item)??0;
  return age===undefined?`no book of ${stop.at}`:age>IGNORE_TICKS?`${stop.at}'s book is ${age} ticks old, past ${IGNORE_TICKS}: no buy for a sale there`
    :`${stop.at}'s book is ${age} ticks old${age>STALE_TICKS?', half its depth counted':''}${claimed?`, ${claimed} claimed by other freighters`:''}`;
}
/** What each item aboard is carried to: the first stop from `from` on round the lap that sells it. */
export function claims(circuit:Circuit,from:number,cargo:Record<string,number>):Claim[] {
  const ring=[...circuit.stops.slice(from),...circuit.stops.slice(0,from)];
  return Object.entries(cargo).flatMap(([item_id,quantity])=>{
    const to=ring.find(stop=>stop.sell.some(sale=>sale.item===item_id));
    return to&&quantity>0?[{base_id:to.at,item_id,quantity}]:[];
  });
}
const free=(f:Freighter)=>{const ship=f.account.state.ship;return Math.max(0,(ship?.cargo_capacity??0)-(ship?.cargo_used??0));};

/** A lost connection rather than the game's answer: the socket closed or never opened, or a
 * mutation's result never came (a half-open socket). Matched on the message too, never thrown on. */
export const dropped=(error:unknown)=>error instanceof ConnectionClosedError||
  /closed socket|connection closed|failed before open|No action_result|timed out/i.test(message(error));

/** What a failed step threw before the `Game` layer tagged it: the lib's own error, or the freighter's own class. */
const raw=(failure:unknown)=>rawError(Cause.fail(failure));

/** Why a failure ends the circuit, or null when the stop is worth redoing. */
function parked(failure:unknown):string|null {
  const error=raw(failure),text=message(error);
  if(/session_replaced|disconnected/i.test(text)||field(error,'code')===4001)return 'session taken elsewhere';
  if(error instanceof FuelRouteShortfall)return `fuel shortfall: ${text}`;
  // A quote the world moved under is a race, redone; any other refusal to fly is the route's.
  if(error instanceof TravelBlocked&&!/changed/.test(text))return `travel blocked: ${text}`;
  if(error instanceof ServiceBlocked)return `no credits for fuel: ${text}`;
  return null;
}

/** A game refusal is said, with its code, and skipped. A lost reply is never re-sent: with `landed`, the
 * account re-read says whether it went through (a trade or deposit moved the hold or the wallet), so what it
 * moved is counted once; without, the stop is redone from a fresh read. Anything else goes up. True when the
 * send went through. */
const tried=<E>(f:Freighter,at:string,what:string,send:Effect.Effect<unknown,E,Game>,landed?:Effect.Effect<boolean,SeamFailed,Game>)=>Effect.gen(function*() {
  const sent=yield* Effect.result(send);
  if(Result.isSuccess(sent))return true;
  const failure=sent.failure;
  if(isGameError(failure)&&failure._tag==='ReplyLost'&&landed)return yield* landed;
  if(!isGameError(failure)||failure._tag==='ReplyLost')return yield* Effect.fail(failure);
  f.report({why:`${at}: ${what} refused: ${failure.message} (${failure.code})`});
  return false;
});

/** Tired's service margin is the wallet itself; the reserve is 0, and the fill is checked after. A
 * counter that refuses a service is passed by: the next quote says whether the tank still reaches. */
const serviceEffect=(f:Freighter,stop:Stop)=>tried(f,stop.at,'service',serviceShipEffect(f.account,{mood:'Tired',cells:false,quotes:false}));

/** Fly to `stop` and dock, unless docked there already; how many jumps it took. */
const flyEffect=(f:Freighter,stop:Stop)=>Effect.gen(function*() {
  const {account}=f,game=yield* Game;
  yield* game.refresh;
  if(account.state.location?.docked_at===stop.at)return 0;
  const quote=replyBody(yield* game.command('spacemolt/find_route',{id:stop.at}));
  // find_route says where the base is now; a mobile station moves, so the circuit's system can be stale.
  const target=field(quote,'target_system'),poi=field(quote,'target_poi');
  const now=typeof target==='string'&&target?target:stop.system_id;
  if(now!==stop.system_id){f.report({moved:{at:stop.at,system_id:now}});stop.system_id=now;}
  // A refuel that does not complete is not the flight's failure: the fuel check after it decides. If the
  // flight is short for want of it, the refuel's own failure (no credits, a lost reply) is the why.
  let unserved:Effect.Error<ReturnType<typeof serviceEffect>>|undefined;
  const refuelWith=()=>Effect.gen(function*() {
    const served=yield* Effect.result(serviceEffect(f,stop));
    if(Result.isFailure(served))unserved=served.failure;
  });
  const flown=yield* Effect.result(travelToEffect(account,{system_id:stop.system_id,poi_id:String(poi??stop.at),base_id:stop.at},{maxJumps:null,refuelWith}));
  // Only a flight short of fuel is the refuel's: a refuel lost but landed, then a route blocked, parks as blocked.
  if(Result.isFailure(flown))return yield* Effect.fail(flown.failure instanceof FuelRouteShortfall?unserved??flown.failure:flown.failure);
  return flown.success.jumps;
});

/** One stop: fly there and dock, service, sell the listed items at their floors, sell the `leftover`
 * (cargo bought that the circuit never sells) where the bid covers its cost a unit, stow what `stow`
 * names that is still there, cheapest a unit first, until `FREE_HOLD` of the hold is free, buy each listed item within its cap and what `plan` says
 * the `later` stops (the rest of the ring, round to this one) take above its cost, one command each,
 * send the credits above the float home. Returns how many trades took, the book's tick, and whether
 * a buy was cut for a later stop with no book to go by (`scouted`: this lap learns it). */
const visitEffect=(f:Freighter,stop:Stop,later:readonly Stop[],leftover:Holding,stow:(item:string)=>boolean,sent:(credits:number)=>void,
  bought:(item:string,n:number,spent:number)=>void,stowed:(item:string,n:number)=>void)=>Effect.gen(function*() {
  const {account}=f,game=yield* Game,send=(action:string,params:Record<string,unknown>)=>game.command(action,params);
  const hold=(item:string)=>miningInventory(account.state)[item]??0,wallet=()=>account.state.player?.credits??0;
  // A trade or deposit whose reply was lost, judged by the account re-read: what it moved is what landed.
  const moved=(item:string,was:number)=>Effect.map(game.refresh,()=>hold(item)!==was);
  yield* flyEffect(f,stop);
  yield* serviceEffect(f,stop);
  // Arrived: what fell short at the last stop, or on the way here, is no longer so.
  f.report({stop:stop.at,why:undefined});
  const reply=replyBody(yield* send('spacemolt_market/view_market',{}));
  const items=rows(field(reply,'items')).flatMap(readRow);
  const book=new Map<string,MarketListingItem>(items.map(row=>[row.item_id,row]));
  const now=num(reply,'current_tick')??0;
  f.market?.saw(stop.at,{tick:now,items});
  yield* fileIntelEffect(account,stop.at,items,now,why=>f.report({why}));
  let traded=0;
  for(const {item,min_price} of stop.sell) {
    const row=book.get(item),held=hold(item);
    // ponytail: the book is read once and the sale sent at market, so a bid pulled in between can
    // fill a unit under the floor. The game takes no limit price on `sell`; a sell order would.
    const n=Math.min(held,(row?levels(row.buy_orders,row.best_buy,row.best_buy_qty):[])
      .filter(level=>level.price_each>=min_price).reduce((sum,level)=>sum+level.quantity,0));
    if(n&&(yield* tried(f,stop.at,`sell ${n} ${item}`,send('spacemolt/sell',{id:item,quantity:n}),moved(item,held))))traded++;
  }
  // Leftover from an old circuit: sold here only at a bid that covers what it cost, freeing the hold.
  for(const [item,lot] of Object.entries(leftover)) {
    const row=book.get(item),unit=lot.cost/lot.quantity;
    let n=0,gross=0;
    for(const level of row?levels(row.buy_orders,row.best_buy,row.best_buy_qty):[]) {
      const take=Math.min(level.quantity,Math.min(lot.quantity,miningInventory(account.state)[item]??0)-n);
      if(level.price_each<unit||take<=0)break;
      n+=take;gross+=take*level.price_each;
    }
    if(!(n&&(yield* tried(f,stop.at,`sell ${n} ${item}`,send('spacemolt/sell',{id:item,quantity:n}),moved(item,hold(item))))))continue;
    traded++;
    f.report({cleared:`cleared ${n} ${item} at ${+(gross/n).toFixed(1)} (cost ${+unit.toFixed(1)})`});
  }
  yield* game.refresh;
  // No stop sells it: into the owner's store here, else the freighter's own, the cheapest a unit
  // first (never bought: 0), only until FREE_HOLD of the hold is free; the rest rides on to clear at cost.
  let need=freeTarget(account.state.ship)-free(f);
  const unit=(item:string)=>{const lot=leftover[item];return lot?lot.cost/lot.quantity:0;};
  for(const [item,held] of Object.entries(miningInventory(account.state)).filter(([item,n])=>n>0&&stow(item)).sort(([a],[b])=>unit(a)-unit(b))) {
    if(need<=0)break;
    const aboard=Math.min(held,need);
    const where=(yield* tried(f,stop.at,`stow ${aboard} ${item} for ${f.owner}`,send('spacemolt_storage/deposit',{target:f.owner,item_id:item,quantity:aboard}),moved(item,held)))
      ?`for ${f.owner}`:(yield* tried(f,stop.at,`stow ${aboard} ${item}`,send('spacemolt_storage/deposit',{item_id:item,quantity:aboard}),moved(item,held)))?'in its own storage':null;
    if(!where)continue;
    // The hold is the evidence, not the reply: what left it is what was stowed.
    yield* game.refresh;
    const n=held-(miningInventory(account.state)[item]??0),lot=leftover[item];
    if(n<=0)continue;
    need-=n;
    const cost=lot&&` (cost ${Math.round(lot.cost*Math.min(n,lot.quantity)/lot.quantity)})`;
    stowed(item,n);
    f.report({stowed:`${n} ${item}${cost??''} at ${stop.at} ${where}`});
  }
  // Recalled: it parks after this stop, so it buys no load it would only strand in the hold.
  const buys=f.recalled()?[]:buysOf(stop);
  // Sized by the planner: this book's asks within the caps, the later stops' bids as the host knows them.
  let sized:Map<string,number>|undefined,scouted=false;
  const shared=f.market;
  const known=shared&&buys.length?yield* Effect.promise(()=>Promise.all(later.map(next=>shared.book(next.at)))):[];
  if(shared&&buys.length) {
    const cargo=miningInventory(account.state);
    const here=planned(f,{...stop,sell:[]},{tick:now,items},now,item=>(buys.find(buy=>buy.item===item)?.qty??0)-(cargo[item]??0));
    const [leg]=plan(cargo,free(f),[{book:here,buy:buys.map(buy=>buy.item),rate:TAX},
      ...later.map((next,i)=>({book:planned(f,next,known[i],now,()=>0),rate:TAX}))]).legs;
    sized=new Map((leg?.buys??[]).map(buy=>[buy.item_id,buy.quantity]));
  }
  for(const {item,qty,max_price} of buys) {
    const row=book.get(item),ship=account.state.ship;
    // ponytail: a unit is one unit of hold. A bulkier item's buy is refused by the game and skipped.
    const cap=Math.min(qty-(miningInventory(account.state)[item]??0),(ship?.cargo_capacity??0)-(ship?.cargo_used??0));
    const want=Math.min(cap,sized?.get(item)??(sized?0:Infinity));
    if(sized&&want<cap) {
      const sellers=later.flatMap((next,i)=>next.sell.some(sale=>sale.item===item)?[{next,known:known[i]}]:[]);
      scouted||=sellers.some(({known})=>!share(ageOf(known,now)));
      f.report({why:`${stop.at}: sized ${item} to ${want} of ${cap}, what the later stops take above cost: `
        +sellers.map(({next,known})=>heard(f,next,known,now,item)).join('; ')});
    }
    let n=0,budget=(account.state.player?.credits??0)-FUEL_MONEY;
    for(const level of row?levels(row.sell_orders,row.best_sell,row.best_sell_qty):[]) {
      if(level.price_each>max_price||n>=want)break;
      const take=Math.max(0,Math.min(want-n,level.quantity,Math.floor(budget/(level.price_each*(1+TAX)))));
      n+=take;budget-=take*level.price_each*(1+TAX);
      if(take<level.quantity)break;
    }
    const before=wallet(),had=hold(item);
    if(!(n>0&&(yield* tried(f,stop.at,`buy ${n} ${item}`,send('spacemolt/buy',{id:item,quantity:n}),moved(item,had)))))continue;
    yield* game.refresh;
    // What came aboard, and what left the wallet for it, tax included: the buy reply's total leaves the tax out.
    traded++;bought(item,hold(item)-had,before-wallet());
  }
  const spare=wallet()-f.float,opened=wallet();
  if(spare>0&&(yield* tried(f,stop.at,`deposit ${spare} cr to ${f.owner}`,send('spacemolt_storage/deposit',{target:f.owner,credits:spare}),
    Effect.map(game.refresh,()=>wallet()<=opened-spare)))) {
    sent(spare);f.report({deposited:spare});
    yield* game.refresh;
  }
  f.report({credits:account.state.player?.credits??0});
  return {traded,tick:now,scouted,items};
});

/** Stops in a row with no trade, laps in a row that lost money, and the cargo at cost, across laps. */
const idle=new WeakMap<Freighter,number>(),losing=new WeakMap<Freighter,number>(),holdings=new WeakMap<Freighter,Holding>();
const worth=(holding:Holding)=>Object.values(holding).reduce((sum,row)=>sum+row.cost,0);
/** Cut `holding` to what is aboard: units gone (sold) take their average cost with them. */
function aboard(holding:Holding,cargo:Record<string,number>):void {
  for(const [item,row] of Object.entries(holding)) {
    const now=Math.min(row.quantity,cargo[item]??0);
    if(now<=0)delete holding[item];
    else if(now<row.quantity)holding[item]={quantity:now,cost:row.cost*now/row.quantity};
  }
}

/** The lap planned before it is flown, from the hold aboard, on the host's books of every stop
 * (`planned`, as each buy is sized), two laps ahead so a buy at the last stop sells at the first. A
 * park, drained, when those plan at 0 or less; undefined when they pay, or when any stop has no book
 * younger than `IGNORE_TICKS` (or no tick is known yet): the lap flies, and its reads decide the next.
 * ponytail: the fuel is not in the planned net; `LOSING_LAPS` backs it. */
const lapPlan=(f:Freighter,circuit:Circuit)=>Effect.gen(function*() {
  const now=f.market?.tick(),shared=f.market;
  if(!shared||!now)return undefined;
  const known=yield* Effect.promise(()=>Promise.all(circuit.stops.map(stop=>shared.book(stop.at))));
  if(!known.every(book=>share(ageOf(book,now))))return undefined;
  // Cargo the circuit never sells is cleared or stowed, not planned: a hold it blocks parks as blocked, not drained.
  // Stowed only until FREE_HOLD is free, so the room is that much at most; what rides on takes the rest.
  const sells=new Set(circuit.stops.flatMap(stop=>stop.sell.map(sale=>sale.item)));
  const aboard=Object.entries(miningInventory(f.account.state)),hold=Object.fromEntries(aboard.filter(([item])=>sells.has(item)));
  const room=Math.max(free(f),Math.min(free(f)+aboard.filter(([item])=>!sells.has(item)).reduce((sum,[,n])=>sum+n,0),freeTarget(f.account.state.ship)));
  const {net}=plan(hold,room,[...circuit.stops,...circuit.stops].map((stop,i)=>({
    book:planned(f,stop,known[i%known.length],now,item=>buysOf(stop).find(buy=>buy.item===item)?.qty??0),buy:buysOf(stop).map(buy=>buy.item),rate:TAX})));
  return net>0?undefined:f.park(`lap planned at ${net} on fresh books (two laps ahead); circuit drained`,now);
});

/** Fly `circuit` once round, stop by stop, from wherever the freighter is. Every failure of a
 * stop is redone or parks it (see the module note), so only a bug fails it. Ends with the lap's net reported. */
export const lapEffect=(f:Freighter,circuit:Circuit)=>Effect.gen(function*() {
  const open=closure(circuit);
  if(open)return f.park(open);
  // A loop (re)starting: `holding` is as last reported, and the freighter wherever it was left.
  const fresh=!holdings.has(f),holding=holdings.get(f)??structuredClone(f.holding??{});
  holdings.set(f,holding);
  const wallet=()=>f.account.state.player?.credits??0;
  // `kept`: what was stowed, at cost; handed over like a deposit home, never a loss of this lap's.
  let home=0,kept=0,tick=0,opening:number|undefined,stocked=0,left:number|undefined,jumps=0;
  const sells=new Set(circuit.stops.flatMap(stop=>stop.sell.map(sale=>sale.item)));
  const cargo=()=>miningInventory(f.account.state);
  f.market?.claim(claims(circuit,0,cargo()));
  const drained=yield* lapPlan(f,circuit);
  if(drained)return drained;
  const game=yield* Game;
  for(const [i,stop] of circuit.stops.entries()) {
    // Stowed at a new circuit's first stop, so lap 1 has FREE_HOLD of the hold, and at every lap's last.
    const stowing=(fresh&&i===0)||i===circuit.stops.length-1;
    let traded=0,scouted=false,tries=0;
    const once=Effect.gen(function*() {
      if(opening===undefined) {
        // The hold as it is, not as last reported: cargo sold by hand while parked is not stock.
        yield* game.refresh;
        aboard(holding,miningInventory(f.account.state));
        stocked=worth(holding);
        // Said at once: the entry `assign` wrote carries the holding as last reported, not as aboard.
        if(fresh)f.report({holding:structuredClone(holding)});
        // Once begun, an approach redone after a failure is still the approach.
        if(fresh&&(left!==undefined||f.account.state.location?.docked_at!==stop.at)) {
          left??=wallet();
          jumps+=yield* flyEffect(f,stop);
          yield* serviceEffect(f,stop);
          f.report({approach:{jumps,credits:left-wallet()}});
        }
        opening=wallet();
      }
      const leftover=Object.fromEntries(Object.entries(holding).filter(([item])=>!sells.has(item)));
      return yield* visitEffect(f,stop,[...circuit.stops.slice(i+1),...circuit.stops.slice(0,i)],leftover,item=>stowing&&!sells.has(item),credits=>{home+=credits;},(item,n,spent)=>{
        const row=holding[item]??={quantity:0,cost:0};row.quantity+=n;row.cost+=spent;},(item,n)=>{
        // Its units leave `holding` with the check after the stop; their cost goes into `kept` now.
        const row=holding[item];if(row)kept+=row.cost*Math.min(n,row.quantity)/row.quantity;});
    });
    for(;;) {
      const visited=yield* Effect.result(once);
      if(Result.isSuccess(visited)){({traded,tick,scouted}=visited.success);break;}
      const failure=visited.failure,why=parked(failure),text=message(raw(failure));
      if(why)return f.park(why);
      // The game's word for a mobile station gone from the system it was flown to; the next try's
      // find_route places it afresh.
      if(/not here right now/i.test(text))f.report({moved:{at:stop.at}});
      if(!dropped(raw(failure))&&++tries>=STOP_TRIES) {
        // Skipped as a stop with no trade: DEAD_STOPS of them park the circuit for a re-plan.
        f.report({why:`${stop.at}: skipped this lap after ${tries} tries: ${text}`});
        traded=0;opening??=wallet();
        break;
      }
      f.report({why:`${stop.at}: ${text}; again in a minute`});
      yield* Effect.sleep(RETRY_MS);
      if(f.recalled())return f.park('recalled');
    }
    aboard(holding,cargo());
    f.report({holding:structuredClone(holding)});
    // What it carries on, claimed at the stop that sells it; what it sold, stowed or cleared is released.
    f.market?.claim(claims(circuit,(i+1)%circuit.stops.length,cargo()));
    // A stop that bought less for want of a book is scouting, not dead: the next lap sizes by what it read.
    const dead=traded||scouted?0:(idle.get(f)??0)+1;
    idle.set(f,dead);
    if(dead>=DEAD_STOPS) {
      // Cargo this circuit never sells, that no store took, keeping the free hold under FREE_HOLD: the ring is not drained.
      const cargo=miningInventory(f.account.state);
      if(free(f)<freeTarget(f.account.state.ship)&&Object.keys(cargo).every(item=>!sells.has(item)))
        return f.park(`hold full of ${Object.entries(cargo).map(([item,n])=>`${n} ${item}`).join(', ')} this circuit never sells, no stop on it bids at or above its cost and storage refused it, so it cannot buy; `
          +'assign it a circuit that sells that cargo',undefined,true);
      return f.park(`circuit dead: ${dead} stops in a row with no trade`,tick);
    }
    if(f.recalled())return f.park('recalled');
  }
  // The wallet's change, plus the change in cargo aboard at cost: a load kept aboard is not a loss.
  const net=Math.round(wallet()+home+kept-(opening??wallet())+worth(holding)-stocked);
  f.report({lapped:net});
  const lost=net>0?0:(losing.get(f)??0)+1;
  losing.set(f,lost);
  if(lost>=LOSING_LAPS)return {...f.park(`${lost} laps lost money: last ${net} vs predicted ${circuit.lap_net}`,tick),net};
  return {net};
});

/** What a freighter's Effect runs on: its own account's send and refresh, never the pilot's. */
const world=(f:Freighter)=>GameLive({send:f.command,refresh:()=>f.account.refresh()});

/** The Promise twin of `lapEffect`, the generated script's `lap` (the frozen freighter surface): only a bug throws, as it was thrown. */
export async function lap(f:Freighter,circuit:Circuit):Promise<Lap> {
  const exit=await Effect.runPromiseExit(lapEffect(f,circuit).pipe(Effect.provide(world(f))));
  if(exit._tag==='Failure')throw rawError(exit.cause);
  return exit.value;
}

/** One scouting hop while the freighter waits for a circuit (the host's `replan`). With `at`: fly
 * there and dock, and do a stop that neither sells a circuit's goods nor buys (`visit` with an empty
 * stop): serviced, the book read and filed, cargo aboard at cost cleared where a bid covers its cost,
 * the credits above the float sent home. Without: fly to `system_id`, undocked, for its bases.
 * STOP_TRIES tries a minute apart; a route that cannot be flown (fuel, a blocked route) is not
 * retried; recalled between tries, it stops. The book read, or why the hop failed. A session taken
 * elsewhere fails with the error that said so. */
export const scoutHopEffect=(f:Freighter,to:{at?:string;system_id:string})=>Effect.gen(function*() {
  const game=yield* Game,holding=structuredClone(f.holding??{});
  const once=Effect.gen(function*() {
    if(!to.at) {
      yield* game.refresh;
      const from=f.account.state.location?.docked_at??'';
      if(f.account.state.location?.system_id!==to.system_id)yield* travelToEffect(f.account,{system_id:to.system_id},
        {maxJumps:null,refuelWith:()=>Effect.asVoid(Effect.result(serviceEffect(f,{at:from,system_id:'',sell:[]})))});
      return {};
    }
    const {tick,items}=yield* visitEffect(f,{at:to.at,system_id:to.system_id,sell:[]},[],holding,()=>false,()=>{},()=>{},()=>{});
    aboard(holding,miningInventory(f.account.state));
    f.report({holding:structuredClone(holding)});
    return {read:{tick,items}};
  });
  for(let tries=1;;) {
    const hop=yield* Effect.result(once);
    if(Result.isSuccess(hop))return hop.success;
    const failure=hop.failure,why=parked(failure),text=message(raw(failure));
    if(why==='session taken elsewhere')return yield* Effect.fail(failure);
    if(why)return {why};
    if(to.at&&/not here right now/i.test(text))f.report({moved:{at:to.at}});
    if(!dropped(raw(failure))&&tries++>=STOP_TRIES)return {why:`skipped after ${tries-1} tries: ${text}`};
    f.report({why:`${to.at??to.system_id}: ${text}; again in a minute`});
    yield* Effect.sleep(RETRY_MS);
    if(f.recalled())return {why:'recalled'};
  }
});

/** The Promise twin of `scoutHopEffect`, kept for the frozen freighter surface (`play/freighter`): a session taken elsewhere, or a bug, throws as it was thrown. The host calls the Effect. */
export async function scoutHop(f:Freighter,to:{at?:string;system_id:string}):Promise<{read?:{tick:number;items:MarketListingItem[]};why?:string}> {
  const exit=await Effect.runPromiseExit(scoutHopEffect(f,to).pipe(Effect.provide(world(f))));
  if(exit._tag==='Failure')throw rawError(exit.cause);
  return exit.value;
}
