/** Where freighters fly from: the pilot's own bridge process, one extra `Account` per freighter.
 * A freighter has no bridge, juncture or pilot record of its own. Its whole state is a row of
 * `freighters.json` in the pilot's runtime dir, its script is `freighters/<name>.ts` (generated by
 * `assign`), and its login is `freighters/<name>.txt`, which the operator puts there.
 *
 * A loop never touches the play runtime singleton: it commands through its own account, and
 * journals into the pilot's journal under a `<name>:` prefix. When its ring drains it re-plans
 * with `search`, the planner `routes()` is, on its own connection and this runtime's files. Not reachable from a pilot file
 * (`play/freighter` resolves to `index.ts`, never here). */
import { Account } from '@spacemolt/lib';
import type { ReadinessAccount, ReadinessCommand } from '../../readiness.ts';
import { type Circuit } from '../trading/trading.ts';
import { type Approach, type Holding, type Market } from './index.ts';
/** One freighter as `freighters.json` keeps it. */
export interface Entry {
    /** `running` flies (and is resumed after a restart); `scouting` has no circuit that qualifies and
     * flies to read the nearest unknown or stale books (`candidates`), re-planning after each; `waiting`
     * has none and nothing left to scout, docked, re-planning every `REPLAN_TICKS` (both resumed so after
     * a restart); `recalling` finishes its stop; `parked` is stopped for good. */
    state: 'running' | 'waiting' | 'scouting' | 'recalling' | 'parked';
    circuit: Circuit;
    float: number;
    owner: string;
    /** Laps completed since it was assigned, the base it is at or was last at, its wallet there. */
    lap: number;
    stop?: string;
    credits?: number;
    /** Credits deposited home to `owner`, all told. */
    returned: number;
    /** The last whole lap's net, against `circuit.lap_net` predicted: the wallet's change plus the
     * change in `holding`. */
    last_lap_net?: number;
    /** The cargo aboard it bought, at cost, after its last stop. */
    holding?: Holding;
    /** Its last flight onto the circuit from where its loop started, kept out of every lap's net. */
    approach?: Approach;
    /** Why it parked, or what fell short at the last stop. */
    why?: string | undefined;
    /** Scheduled to stop at the end of the lap it is on (`recall(name, {after:'lap'})`): it parks
     * then and is not re-planned. `assign` clears it. */
    stop_after_lap?: true;
    /** Its auto-reassigns, all told, and the last one's ring and predicted lap_net. */
    reassigned?: {
        count: number;
        ring: string;
        lap_net: number;
    };
    /** Every stow of cargo no circuit stop sold, oldest first: what, at what cost, where, whose storage. */
    stowed?: string[];
    /** Books it read scouting while it waited for a circuit, all told. */
    scouted?: number;
    at: string;
}
/** A freighter as `freighters()` and the menu report it. */
export interface FreighterRow {
    name: string;
    state: Entry['state'];
    lap: number;
    stop: string | null;
    credits: number | null;
    returned: number;
    last_lap_net: number | null;
    lap_net: number;
    holding: Holding;
    approach?: Approach;
    why?: string;
    stop_after_lap?: true;
    reassigned?: Entry['reassigned'];
    stowed?: string[];
    scouted?: number;
}
/** ponytail: the wait before a failed reconnect is tried again, doubling from RECONNECT_MS to at most
 * RECONNECT_MAX_MS; and how long one reconnect (or the lib's own) may take before it is given up on. */
export declare const RECONNECT_MS = 1000, RECONNECT_MAX_MS = 300000, RECONNECT_WAIT_MS = 60000;
/** A freighter with no circuit that qualifies re-plans this often: a quarter of the rest a drained ring takes. */
export declare const REPLAN_TICKS: number;
export declare const scriptPath: (runtime: string, name: string) => string;
export declare const credentialsPath: (runtime: string, name: string) => string;
export declare function readFleet(runtime: string): Record<string, Entry>;
/** Temp file then rename: a torn write would resume a freighter on a lie. */
export declare function writeFleet(runtime: string, fleet: Record<string, Entry>): void;
export declare const row: (name: string, entry: Entry) => FreighterRow;
/** `holding` in words: `40 copper_piping (1148 cr)`. */
export declare const held: (holding: Holding) => string;
/** The menu's `freighters` rows; nothing when none was ever assigned. */
export declare function fleetBrief(runtime: string): {
    freighters?: FreighterRow[];
};
/** The one script a freighter runs, from a fixed template: the circuit is its only variable. */
export declare function script(circuit: Circuit, at?: string): string;
/** The pilot file's boundary and policy, and one import only: `play/freighter`. */
export declare function gate(path: string): string[];
/** Write `circuit` as `name`'s script and entry, running: only the fields a circuit has (a one-`buy`
 * stop written as `buys`), the gate run on the script, `returned`, `holding` and `reassigned` kept,
 * a stop-after-lap cleared. What `assign` and an auto-reassign both install through. Why it was
 * refused, or null. */
export declare function install(runtime: string, name: string, circuit: Circuit, fields: {
    float: number;
    owner: string;
    reassigned?: Entry['reassigned'];
}): string | null;
/** A flying freighter's switches: `recall` parks it after its stop, `afterLap` after its lap
 * (`lapDone` once that lap has ended), `stopping` is the bridge going. */
interface Loop {
    recall: boolean;
    afterLap: boolean;
    lapDone: boolean;
    stopping: boolean;
    close(): void;
}
export declare const flying: (name: string) => boolean;
/** ponytail: how long one base's book, fetched for one freighter, serves every freighter of this
 * process before it is fetched again: a minute, so N freighters on a ring cost one ledger query a
 * base a minute, not one a stop each. Tunable. */
export declare const BOOK_TTL_MS = 60000;
/** The books and claims `name`'s loop shares with every other freighter this process flies. */
export declare function market(runtime: string, name: string, account: object, command: ReadinessCommand): Market;
/** Log `name` in on its own account and run its loop, detached. Null when it is off; else why
 * not, and the entry is parked with that why. */
export declare function start(runtime: string, name: string): string | null;
/** Reconnects for `account` that never log in twice, and `gone()`: the error once the session is
 * taken for good. A socket can die without closing (live 2026-09-26: each command then hung ~16 minutes
 * until the OS gave up on it), and the lib's own reconnect only starts at a close. So: the lib's
 * reconnect if it is under way or done; else the stale socket is cut loose (its late close, or a 4001
 * when the new login supersedes it, would reach the lib as the current one's, start the lib's own
 * reconnect on top of ours, and a second login would kick ours: live 2026-09-26, a parked "session
 * taken elsewhere" nobody else took) and a fresh socket and login forced in place. The lib reports a
 * close it will not reconnect through (4001/4002) by `onDisconnected`; that parks only when the
 * current connection fails a status read too. */
export declare function mender(account: Account): {
    reconnect: (error: unknown) => Promise<void>;
    gone: () => Error | undefined;
};
/** Run `name`'s loop on `account`, logged in by `login`: its script lap after lap, re-planned when
 * its ring drains. Resolves once it has stopped; the entry says how. What `start` runs detached. */
export declare function launch(runtime: string, name: string, account: ReadinessAccount, command: ReadinessCommand, opts?: {
    login?: (loop: Loop) => Promise<void>;
    close?: () => void;
    unlock?: () => void;
    reconnect?: (error: unknown) => Promise<void>;
}): Promise<void>;
/** Ask `name` home. It finishes the stop it is on, deposits, and parks docked with its cargo. With
 * `after:'lap'`, it finishes the lap it is on instead, selling as usual. Either way it is not re-planned. */
export declare function recallLoop(runtime: string, name: string, after?: 'lap'): string | null;
/** After a bridge restart: every `running` or `waiting` freighter flies again, every `recalling` one is parked. */
export declare function resumeFreighters(runtime: string): void;
/** The bridge is going: close every freighter's account and leave its entry as it is. */
export declare function stopFreighters(): void;
export {};
