/** A freighter: a second account that flies one closed circuit over and over, with no pilot of its
 * own. Its script is generated by `assign` and does one thing, `lap(f, CIRCUIT)` until recalled;
 * the host (`host.ts`) logs it in and hands it `f`. Nothing here touches the play runtime: a
 * freighter's commands go through its own account, never the pilot's.
 *
 * Every failure is handled here, once, so the script stays a loop:
 * - a disconnect or any other throw: wait a minute and redo the stop from a fresh read. A stop is
 *   idempotent: sales are sized by what is held, each buy by the free hold and what is already aboard.
 *   The why it said clears once the stop is reached. STOP_TRIES failed tries in a row skip the stop
 *   for the lap, as a stop with no trade, so no stop can hold a freighter forever. A lost connection
 *   (`dropped`) is not a try: the host reconnects before it reaches here, and the stop is redone;
 * - a base away from the circuit's system for it (a mobile station): each flight goes to the system
 *   `find_route` names for the base now, and the move is reported for the host to record;
 * - the session taken by another connection: park, and never log in again;
 * - cargo it bought that the circuit never sells (left from an old circuit): sold at any stop whose
 *   bid covers its cost a unit, after the stop's own sales and before its buys; never at a loss, and
 *   cargo it never bought (cost unknown) is never sold;
 * - cargo aboard the circuit never sells, bought or not, at a new circuit's first stop or at a lap's
 *   last stop, after the sales and before the buys: stowed there, the cheapest a unit first (never
 *   bought counts as 0), only until `FREE_HOLD` of the hold is free, into the owner's storage
 *   (`deposit` with `target`), else its own; the rest rides along, cleared at cost where a bid covers it;
 * - a sale or buy the game refuses: say so and go on; three stops in a row with no trade parks it,
 *   the ring recorded as drained, unless cargo the circuit never sells, that neither a bid nor a store
 *   took, holds the free hold under `FREE_HOLD`: then the why names that cargo and the ring is not drained;
 * - recalled: it buys nothing more, and parks after the stop it is on;
 * - a route short of fuel, a blocked flight, no credits for fuel: park, docked where it is;
 * - LOSING_LAPS laps in a row that net 0 or less: park, docked at the lap's last stop, the ring drained.
 * With a host's `market` (always, flown from a host), each buy is sized by `plan`, the one planner,
 * against the live book here and the freshest known books of the lap's later stops, and each lap
 * starts by planning the whole lap: one that plans at 0 or less on fresh books parks drained unflown.
 * A parked ship keeps the circuit's cargo aboard, and `holding` says what it cost. A drained or blocked park is
 * the host's to re-plan (`host.ts`); the script only parks. */
import { type MarketListingItem } from '@spacemolt/lib';
import type { ReadinessAccount, ReadinessCommand } from '../../readiness.ts';
import { type Circuit, type Listing } from '../trading/trading.ts';
/** What one lap did: `park` when the freighter stopped for good, and why; `net` the credits it
 * made, deposits home included, with the cargo aboard at its cost (see `Holding`). */
export interface Lap {
    park?: string;
    net: number;
}
/** The cargo aboard that the freighter bought, per item: units and what they cost, tax included.
 * A sale takes units off at their average cost; units aboard it never bought are not in it. */
export type Holding = Record<string, {
    quantity: number;
    cost: number;
}>;
/** The flight to a circuit's first stop from wherever the loop started, off the circuit: its jumps
 * and what it cost, fuel and repairs on arrival included. Never part of a lap's net. */
export interface Approach {
    jumps: number;
    credits: number;
}
/** What a freighter says as it goes. `deposited` is one deposit home; `lapped` a whole lap's net;
 * `holding` the cargo aboard at cost, after each stop; `approach` the flight onto the circuit;
 * `cleared` leftover cargo sold at cost or better, e.g. "cleared 98 copper_piping at 36 (cost 29.6)";
 * `stowed` cargo the circuit never sells put in storage, e.g. "98 copper_piping (cost 2898) at
 * nova_terra_central for Chrisjen Avasarala", or "… in its own storage" when the owner's was refused. */
export interface Report {
    stop?: string;
    credits?: number;
    deposited?: number;
    lapped?: number;
    holding?: Holding;
    approach?: Approach;
    cleared?: string;
    stowed?: string;
    why?: string | undefined;
    /** A stop's base found away from the system the circuit kept for it: a mobile station. `system_id`
     * where `find_route` places it now, when known. The host records it mobile and re-places it. */
    moved?: {
        at: string;
        system_id?: string;
    };
}
/** A base's book as the host knows it: rows, and the game tick it was read or filed on. */
export interface Known {
    tick: number;
    items: Listing[];
}
/** One freighter's claim on a base's bids: units aboard it carries there to sell. */
export interface Claim {
    base_id: string;
    item_id: string;
    quantity: number;
}
/** What a host shares between its freighters (`host.ts`): books and depth claims. */
export interface Market {
    /** The freshest book known for `base_id`: the faction ledger's (cached `BOOK_TTL_MS`), a live read
     * by any freighter of the host, or the owner's market memory. Never throws. */
    book(base_id: string): Promise<Known | undefined>;
    /** A live read at `base_id`, kept for every freighter of the host. */
    saw(base_id: string, known: Known): void;
    /** The latest game tick any freighter of the host has read; 0 before any. */
    tick(): number;
    /** Units of `item_id` the host's other freighters carry to sell at `base_id`. */
    claimed(base_id: string, item_id: string): number;
    /** This freighter's claims now, replacing its last. */
    claim(rows: Claim[]): void;
}
/** What the host hands a freighter's script. */
export interface Freighter {
    name: string;
    /** The freighter's own account and command seam, logged in by the host. */
    account: ReadinessAccount;
    command: ReadinessCommand;
    /** The player its profit goes home to, and the credits it keeps aboard to trade with. */
    owner: string;
    float: number;
    /** The cargo aboard at cost when it was started, as last reported. */
    holding?: Holding;
    /** True once `recall` asked it home: it finishes the stop it is on and parks. */
    recalled(): boolean;
    /** Stop with `why`; the Lap to return. `drained`, the game tick, when the circuit's books ran dry
     * (no trade, or laps that lost money): the host records the ring as resting and re-plans. `blocked`
     * when the hold is full of cargo the circuit never sells: the host re-plans, the ring not drained. */
    park(why: string, drained?: number, blocked?: boolean): Lap;
    report(fields: Report): void;
    /** The host's books and claims. Absent (a bare `lap` in a test), buys are sized by the circuit's caps alone. */
    market?: Market;
}
/** ponytail: the share of the hold a stow frees, and no more: cargo the circuit never sells is stowed
 * only down to this much free, the rest kept aboard to clear at cost. Operator's call: a big hauler
 * still buys at a profit into 40%. Tunable. */
export declare const FREE_HOLD = 0.4;
/** The free hold a stow aims at: `FREE_HOLD` of the hold, whole units. */
export declare const freeTarget: (ship: {
    cargo_capacity?: number;
} | undefined) => number;
/** A later stop's book older than this many ticks (30 minutes at ten seconds a tick) counts at half
 * its depth when a buy is sized: NPC books move rarely, but other traders fill bids. */
export declare const STALE_TICKS = 180;
/** ponytail: past this many ticks (3 hours) a later stop's book justifies no buy for a sale there;
 * the lap visits it, and its fresh read sizes the next lap. Tunable. */
export declare const IGNORE_TICKS = 1080;
/** Why `circuit` cannot be flown as a repeating lap, or null. The shape alone: `assign` checks the
 * bases against what is known as well; a lap needs only each stop's `system_id`, as it reads books live. */
export declare function closure(circuit: Circuit): string | null;
/** What each item aboard is carried to: the first stop from `from` on round the lap that sells it. */
export declare function claims(circuit: Circuit, from: number, cargo: Record<string, number>): Claim[];
/** A lost connection rather than the game's answer: the socket closed or never opened, or a
 * mutation's result never came (a half-open socket). Matched on the message too, never thrown on. */
export declare const dropped: (error: unknown) => boolean;
/** Fly `circuit` once round, stop by stop, from wherever the freighter is. Never throws: every
 * failure is redone or parks it (see the module note). Ends with the lap's net reported. */
export declare function lap(f: Freighter, circuit: Circuit): Promise<Lap>;
/** One scouting hop while the freighter waits for a circuit (the host's `replan`). With `at`: fly
 * there and dock, and do a stop that neither sells a circuit's goods nor buys (`visit` with an empty
 * stop): serviced, the book read and filed, cargo aboard at cost cleared where a bid covers its cost,
 * the credits above the float sent home. Without: fly to `system_id`, undocked, for its bases.
 * STOP_TRIES tries a minute apart; a route that cannot be flown (fuel, a blocked route) is not
 * retried; recalled between tries, it stops. The book read, or why the hop failed. A session taken
 * elsewhere throws. */
export declare function scoutHop(f: Freighter, to: {
    at?: string;
    system_id: string;
}): Promise<{
    read?: {
        tick: number;
        items: MarketListingItem[];
    };
    why?: string;
}>;
