// Generates src/wire.gen.ts (an Effect Schema for every OpenAPI component of the installed
// @spacemolt/lib) and src/wire-drift.gen.ts (a compile-time proof that each one equals the lib's
// type). docs/EFFECT.md §Generating the wire schemas names the known cases handled here.
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {SchemaRepresentation, type JsonSchema} from 'effect';
import ts from 'typescript';

const root = fileURLToPath(new URL('..', import.meta.url));
const fail = (msg: string): never => { console.error(msg); process.exit(1); };
const isRecord = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);

const pkg: unknown = JSON.parse(readFileSync(`${root}node_modules/@spacemolt/lib/package.json`, 'utf8'));
const version = isRecord(pkg) && typeof pkg.version === 'string' ? pkg.version : fail('no @spacemolt/lib version');
const url = `https://raw.githubusercontent.com/SpaceMolt/spacemolt-lib/v${version}/openapi.json`;
const res = await fetch(url);
if (!res.ok) fail(`${url}: ${res.status}`);
const spec: unknown = JSON.parse((await res.text()).replaceAll('#/components/schemas/', '#/$defs/'));
const schemas = isRecord(spec) && isRecord(spec.components) && isRecord(spec.components.schemas) ? spec.components.schemas : fail('openapi.json has no components.schemas');
const definitions: JsonSchema.Definitions = {};
for (const [n, s] of Object.entries(schemas)) definitions[n] = isRecord(s) ? s : fail(`component ${n} is not an object`);
const names = Object.keys(definitions);

// Patterns: three components reach a patternProperties, which the default ('error') refuses.
const asts = names.flatMap(n => {
  try { return [SchemaRepresentation.fromJsonSchemaDocument({dialect: 'draft-2020-12', schema: {$ref: `#/$defs/${n}`}, definitions}, {patterns: 'apply'}).ast]; }
  catch (e) { console.error('FAIL', n, String(e)); return []; }
});
console.log(`imported ${asts.length}/${names.length}`);
const [first, ...rest] = asts;
if (first === undefined || asts.length !== names.length) fail('import failed');
// Open values: the importer types them Schema.Json, the lib types them unknown. The casts are the generator's own.
const unjson = (v: unknown): unknown => {
  if (Array.isArray(v)) return v.map(unjson);
  if (v === null || typeof v !== 'object' || Object.getPrototypeOf(v) !== Object.prototype) return v;
  const o = v as {_tag?: unknown; representation?: {id?: unknown}; annotations?: object};
  if (o._tag === 'Declaration' && o.representation?.id === 'effect/schema/Json') {
    const {expected: _, ...annotations} = (o.annotations ?? {}) as Record<string, unknown>;
    return {_tag: 'Unknown', annotations, checks: []};
  }
  return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, unjson(x)]));
};
const reps = SchemaRepresentation.toRepresentations([first ?? fail('import failed'), ...rest]);
const doc = SchemaRepresentation.toCodeDocument(unjson(reps) as typeof reps);
if (Object.keys(doc.references.recursives).length) fail('recursive references: the generator does not emit them yet');
if (doc.artifacts.length) fail(`unexpected artifacts: ${JSON.stringify(doc.artifacts).slice(0, 300)}`);

// Contextual duplicates come out as X_1 among the references; a root whose code is its own name is one of them.
const header = `// Generated by scripts/gen-wire.ts from @spacemolt/lib ${version}. Do not edit; run npm run gen:wire.`;
const out = [header, "import {Schema} from 'effect';"];
const exported = new Set<string>();
for (const r of doc.references.nonRecursives) { out.push(`export const ${r.$ref} = ${r.code.runtime};`); exported.add(r.$ref); }
doc.codes.forEach((c, i) => {
  const n = names[i];
  if (n !== undefined && c.runtime !== n && !exported.has(n)) { out.push(`export const ${n} = ${c.runtime};`); exported.add(n); }
});
// Suspended references name a type X that must exist beside the const.
for (const n of new Set([...out.join('\n').matchAll(/Schema\.Codec<(\w+)>/g)].map(m => m[1]))) out.push(`export type ${n} = typeof ${n}.Type;`);
const wire = out.join('\n') + '\n';
writeFileSync(`${root}src/wire.gen.ts`, wire);
console.log(`wire.gen.ts: ${exported.size} schemas, ${Buffer.byteLength(wire)} bytes`);

// Shadowed names: assert only names whose public export is the generated OpenAPI type (the lib's MapSystem is not).
const options: ts.CompilerOptions = {module: ts.ModuleKind.NodeNext, moduleResolution: ts.ModuleResolutionKind.NodeNext, noEmit: true};
const entry = ts.resolveModuleName('@spacemolt/lib', `${root}scripts/gen-wire.ts`, options, ts.sys).resolvedModule?.resolvedFileName ?? fail('cannot resolve @spacemolt/lib');
const prog = ts.createProgram([entry], options);
const chk = prog.getTypeChecker();
const exportsOf = (f: ts.SourceFile | undefined) => { const s = f && chk.getSymbolAtLocation(f); return s ? chk.getExportsOfModule(s) : fail(`no module symbol for ${f?.fileName}`); };
const declared = (s: ts.Symbol) => chk.getDeclaredTypeOfSymbol(s.flags & ts.SymbolFlags.Alias ? chk.getAliasedSymbol(s) : s);
const gen = new Map(exportsOf(prog.getSourceFiles().find(f => f.fileName.endsWith('/openapi/types.gen.d.ts'))).map(s => [s.name, declared(s)]));
const lib = new Set(exportsOf(prog.getSourceFile(entry)).filter(s => gen.get(s.name) === declared(s)).map(s => s.name));
const asserted = names.filter(n => lib.has(n));
console.log('shadowed', names.filter(n => gen.has(n) && !lib.has(n)));

// The lib's own bugs, each patched on the lib side up through every asserted component that reaches it.
// Its generator drops patternProperties, so side_factions' values are never; the spec says string.
// It reads NotificationOk.base's type ["string","object","null"] as object | object | null, dropping string.
const patches: Record<string, string> = {
  RecoveredBattleSummary: `Omit<L.RecoveredBattleSummary, 'side_factions'> & {side_factions?: {[key: string]: string}}`,
  BattleLogEntry: `Omit<L.BattleLogEntry, 'recovered_summary'> & {recovered_summary?: Lib_RecoveredBattleSummary}`,
  GetBattleLogResponse: `Omit<L.GetBattleLogResponse, 'entries'> & {entries: Array<Lib_BattleLogEntry>}`,
  NotificationOk: `Omit<L.NotificationOk, 'base'> & {base?: string | {[key: string]: unknown} | null}`,
  NotificationPayload: `Exclude<L.NotificationPayload, L.NotificationOk> | Lib_NotificationOk`,
  McpNotification: `Omit<L.McpNotification, 'data'> & {data: Lib_NotificationPayload}`,
  GetNotificationsResponse: `Omit<L.GetNotificationsResponse, 'notifications'> & {notifications: Array<Lib_McpNotification>}`,
  V2Response: `Omit<L.V2Response, 'notifications'> & {notifications?: Array<Omit<NonNullable<L.V2Response['notifications']>[number], 'data'> & {data?: Lib_NotificationPayload}>}`,
};
const drift = [
  header, `import type * as L from '@spacemolt/lib';`, `import type * as Wire from './wire.gen.ts';`,
  `type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;`,
  `type M<T> = unknown extends T ? T : {-readonly [K in keyof T]: M<T[K]>};`,
  `// Each fails once the lib types its field as the spec does; then that bug's Lib_ patches come out.`,
  `export const _libBugSideFactions: Same<NonNullable<L.RecoveredBattleSummary['side_factions']>, {[key: string]: never}> = true;`,
  `export const _libBugBase: Same<NonNullable<L.NotificationOk['base']>, {[key: string]: unknown}> = true;`,
  ...Object.entries(patches).map(([n, t]) => `type Lib_${n} = ${t};`),
  ...asserted.map(n => `export const _${n}: Same<M<typeof Wire.${n}.Type>, ${patches[n] ? `Lib_${n}` : `L.${n}`}> = true;`),
];
writeFileSync(`${root}src/wire-drift.gen.ts`, drift.join('\n') + '\n');
console.log(`wire-drift.gen.ts: ${asserted.length} assertions`);
