const p=(name:string,type:string,description:string,required=false)=>({name,type,description,required});
const budget=[p('max_spend','number','Maximum input purchases and crafting fees for this experiment; default 1000.'),p('credit_reserve','number','Minimum remaining wallet; default 150000.'),p('min_profit','number','Minimum predicted profit; for inventory subtract raw sale opportunity cost. Default 1.')];
const recipe=[p('recipe_id','string','Exact recipe id from screen/recipes.',true),p('quantity','number','Desired output count, rounded to whole runs.'),p('source','string','buy to purchase fresh inputs; inventory to process owned storage and carried inputs; deposits only recipe shortfalls from cargo and accounts for raw sale opportunity.')];
export const industryCatalog:Record<string,unknown>={
  'industry/survey':{kind:'mutation',summary:'Visit up to three verified nearby public stations and run market discovery at each. At most two normal jumps per leg, with bounded total jump/fuel reserves. Returns to origin by default; no trades or service purchases. Records comparisons and unpriced travel fuel.',params:[p('station_ids','string[]','One to three public station base or POI IDs.',true),p('max_total_jumps','number','Total jump cap including return, default 6, maximum 8.'),p('min_fuel_reserve','number','Fuel kept after planned travel, default 10.'),p('credit_reserve','number','Wallet reserve, default 150000.'),p('return_to_origin','boolean','Return to original docked station after discovery, default true.')]},
  'industry/discover':{kind:'query',summary:'Separate current income quotes from supplied learning probes and skill-gated future hypotheses. No projected XP or future-profit multiplier. Mechanically discover current-station production opportunities: screen market books, diversify recipes by output/material, dry-run quote a bounded set, and rank net economic profit/time plus blocked hypotheses. No purchases or production. Saves observations for location comparisons.',params:[p('max_learning_loss','number','Optional loss cap for identifying learning probes; default zero. Does not authorize production without an explicit learning goal.'),p('limit','number','Maximum dry-run quotes, default 6, range 1..12.')]},
  'industry/locations':{kind:'query',summary:'Find nearby stations from the public map and station directory without traveling. Returns names, IDs, services and minimum jump counts; resource and market profitability remain unobserved.',params:[p('max_jumps','number','Search radius in jumps, default 2, range 1..5.'),p('limit','number','Maximum stations returned, default 10, at most 30.')]},
  'industry/recommend':{kind:'query',summary:'Compare income and learning separately; observed skill progress and changed skill context trigger re-evaluation of earlier outcomes. Choose what to repeat or explore from measured recipe/location/source outcomes. Economic profits replenish an exploration allowance; losses consume it. Wallet reserve and fresh-quote requirements apply. Recommendations are not price guarantees.',params:[p('max_learning_loss','number','Optional loss cap for identifying learning probes; default zero. Does not authorize production without an explicit learning goal.'),p('credit_reserve','number','Wallet reserve, default 150000.'),p('exploration_budget','number','Initial experimental loss allowance, default 1000.'),p('reinvest_fraction','number','Share of verified positive economic profits available for exploration, default 0.25.'),p('max_spend','number','Cap per new experiment, default 1000.')]},
  'industry/mine':{kind:'mutation',summary:'Run one bounded mining experiment (same system or at most two normal jumps each way): verify/refit owned laser, travel to the chosen POI, mine, return, sell only new resources or retain chosen inputs in personal storage for crafting, and record actual yield/profit. Starts docked. Without a caller-supported fuel quote, reports fuel liability instead of claiming fully serviced profit.',params:[p('poi_id','string','Known mining POI at destination.',true),p('target_system_id','string','Optional destination system ID. Requires a verified normal route of at most 2 jumps each way; returns to the original station. Extra jump fuel/time and loaded-return fuel reserve are measured.'),p('cycles','number','Mining attempts, default 3, maximum 20.'),p('retain_items','string[]','Newly mined item IDs to deposit in personal station storage instead of selling. Original cargo is preserved; retained stock is not booked as profit.'),p('credit_reserve','number','Minimum wallet reserve, default 150000.'),p('max_service_spend','number','Maximum refueling/repair spend, default zero.'),p('refuel_unit_quote','number','Observed current return-station cost per fuel including tax; omit if unknown.'),p('min_fuel_reserve','number','Fuel retained during mining, default 10.')]},
  'industry/settle':{kind:'mutation',summary:'Resume settlement of an existing production experiment, including pending craft or unsold output. Never purchases inputs or requeues the craft.',params:[p('experiment_id','string','Saved experiment id.'),p('job_id','string','Existing crafting job id, alternative lookup.'),p('max_wait_seconds','number','Wait for pending work, 0..600.')]},
  'industry/screen':{kind:'query',summary:'Evaluate recipes at this station against live finite market depth and owned inventory. Returns preliminary margins and unknowns; use quote before execution. Saves location observations for future comparison.',params:[p('limit','number','Maximum candidates, default 15, at most 50.')]},
  'industry/recipes':{kind:'query',summary:'Discover current public catalog recipes, including facility-only recipes. Filter by input or output item.',params:[p('item_id','string','Input or output item to match.'),p('limit','number','Maximum recipes, default 30, at most 100.')]},
  'industry/quote':{kind:'query',summary:'Evaluate a specific recipe/location/source/quantity using live crafting quote, purchase taxes and full market depth. Compares processing versus selling inputs raw.',params:recipe},
  'industry/produce':{kind:'mutation',summary:'Run one bounded buy-or-inventory/craft/sell experiment after fresh quote and budget/profit checks. Queues once, verifies produced storage, sells outputs, and records predicted versus realized results. Pending jobs are reported, never automatically requeued.',params:[...recipe,...budget,p('learning_goal','string','Explicit learning objective; together with positive max_learning_loss permits a bounded predicted economic loss for measuring progression.'),p('max_learning_loss','number','Maximum predicted economic loss allowed only with a nonempty learning_goal. Actual execution can differ and is recorded. Does not relax spend, reserve, supply or demand checks.'),p('max_wait_seconds','number','Wait budget for queued craft, default 300, maximum 600.')]},
  'industry/prepare_mining':{kind:'mutation',summary:'Inspect ship readiness and optionally execute verified refit using owned mining laser; preserves survey scanner and cargo expansion. No gear purchases. Dock first.',params:[p('execute','boolean','Apply the readiness plan if true; default false.'),p('min_free_cargo','number','Required free cargo, default 20.'),p('min_fuel','number','Required fuel reserve, default 10.'),p('credit_reserve','number','Required wallet reserve, default 150000.')]},
  'industry/history':{kind:'query',summary:'Review completed/pending experiments and market observations across locations. Use realized profits to fund bounded exploration, and revalidate stale estimates before repetition.',params:[]},
};
