import {test} from 'node:test';
import assert from 'node:assert/strict';
import {gatherFixture} from './gather-fixture.ts';
import {Execution} from './execution.ts';
import {ExecutionStore} from './execution-store.ts';
import {resolveContext} from './execution-policy.ts';
import {jobSpending} from './spending.ts';

test('an objective continues after repaired readiness and repeated gathering while every job spends the original cumulative allowance',async t=>{
  const f=gatherFixture(t);
  f.execution.context=resolveContext({stop_condition:'objective',limits:{max_spend:50}},f.execution.context);
  await f.choose();
  const miner=f.state.modules.pop();
  const blocked:any=await f.execution.dispatch('gather',{poi_id:'belt',cycles:10});
  assert.equal(blocked.status,'blocked');
  assert.match(blocked.error,/mining preparation blocked/);
  assert.equal(f.execution.stopped(),false);
  assert.equal(f.calls.some(call=>call.key==='spacemolt/mine'),false);
  f.state.modules.push(miner);
  const assessed:any=await f.execution.dispatch('assess',{poi_id:'belt'});
  assert.equal(assessed.status,'ready_to_verify_resources');
  const first:any=await f.execution.dispatch('gather',{poi_id:'belt',cycles:10});
  assert.equal(first.status,'completed');
  assert.equal(first.result.gather.cycles_completed,10);
  assert.equal(first.stopping_reason,undefined);
  f.execution.plan({objective:'Craft next after gathering additional carbon'});f.execution.handoff();
  const second:any=await f.execution.dispatch('gather',{poi_id:'belt',cycles:1});
  assert.equal(second.status,'completed');
  assert.equal(second.budget_spending.gross_spend,first.spending.gross_spend+second.spending.gross_spend);
  const returned:any=await f.execution.dispatch('return_to_base');
  assert.equal(returned.status,'returned_to_base');
  assert.equal(f.execution.stopped(),false);
  const third:any=await f.execution.dispatch('gather',{poi_id:'belt',cycles:1});
  assert.equal(third.status,'blocked');
  assert.ok(third.budget_spending.gross_spend<=50);
  assert.equal(third.budget_spending.max_spend,50);
  assert.equal(third.budget_spending.gross_spend,f.store.runJobs().reduce((total,job)=>total+jobSpending(job).known_gross_spend,0));
  const resumed=new Execution(f.account,new ExecutionStore(f.directory,'pilot'),f.execution.context,f.execution.deps);
  resumed.plan({mood:'Focused',objective:'Repair without new spending authorization'});resumed.handoff();
  const repair:any=await resumed.dispatch('prepare');
  assert.equal(repair.status,'blocked');
  assert.equal(repair.budget_spending.max_spend,50);
  assert.equal(repair.budget_spending.gross_spend,third.budget_spending.gross_spend);
});

test('legacy terminal or explicit Tired stops require an explicit non-Tired objective plan; resumption preserves spending and never bypasses uncertainty',async t=>{
  const f=gatherFixture(t);await f.choose();
  const previous:any=await f.execution.dispatch('gather',{poi_id:'belt',cycles:1});
  assert.equal(f.execution.stopped(),true);
  const context=resolveContext({stop_condition:'objective'},f.execution.context);
  const execution=new Execution(f.account,new ExecutionStore(f.directory,'pilot'),context,f.execution.deps);
  assert.equal(execution.stopped(),true);
  await assert.rejects(execution.dispatch('plan',{objective:'New task'}),/latched/);
  f.state.location.docked_at=null;f.state.ship.fuel=99;
  await execution.dispatch('observe');
  await execution.dispatch('plan',{mood:'Focused',objective:'Resume the requested objective'});execution.handoff();
  assert.equal(execution.stopped(),false);
  const returned:any=await execution.dispatch('return_to_base');
  assert.equal(returned.status,'returned_to_base');
  assert.equal(returned.budget_spending.gross_spend,previous.spending.gross_spend+returned.spending.gross_spend);
  const afterResume=new Execution(f.account,new ExecutionStore(f.directory,'pilot'),context,f.execution.deps);
  assert.equal(afterResume.stopped(),false);
  assert.equal(afterResume.store.data.run_start_job,execution.store.data.run_start_job);
  execution.signal('User explicitly asked to stop');
  await assert.rejects(execution.dispatch('gather',{poi_id:'belt',cycles:1}),/admission closed/);
  await execution.dispatch('observe');
  assert.equal(execution.stopped(),true);
  await execution.dispatch('plan',{mood:'Focused'});
  execution.signal('New Tired signal after the resume plan');execution.handoff();
  assert.equal(execution.stopped(),true);
  await execution.dispatch('plan',{mood:'Focused'});execution.handoff();
  assert.equal(execution.stopped(),false);
  const unknown=execution.store.data.jobs.at(-1)!;
  unknown.status='needs_reconciliation';
  unknown.actions.push({action:'spacemolt/mine',params:{},status:'uncertain'});execution.store.save();
  const restarted=new Execution(f.account,new ExecutionStore(f.directory,'pilot'),context,f.execution.deps);
  await assert.rejects(restarted.dispatch('plan',{mood:'Focused'}),/unfinished job requires reconciliation/);
  await assert.rejects(restarted.dispatch('gather',{poi_id:'belt',cycles:1}),/unfinished job requires reconciliation/);
});
